apiVersion: v1
kind: ConfigMap
metadata:
  name: zabbix-app-cm
  namespace: monitoring
data:
  DB_SERVER_HOST: "10.10.0.9"
  DB_SERVER_PORT: 5432
  POSTGRES_DB: zabbix
  ZBX_ENABLE_SNMP_TRAPS: "true"
  ZBX_JAVAGATEWAY_ENABLE: "true"
  ZBX_JAVAGATEWAY: "zbx-java-gateway.local"
  ZBX_STARTJAVAPOLLERS: "5"
  ZBX_SERVER_NAME: "Sindria Zabbix"
  ZBX_SERVER_HOST: "zabbix-server"
  ZBX_SERVER_PORT: "10051"
  PHP_TZ: "Europe/Rome"
  ZBX_HOSTNAME: "zabbix-server.local"
  ZBX_DEBUGLEVEL: "4"
  ZBX_ALLOWEDIP: "zbx-server.local"
  ZBX_WEBSERVICEURL: "http://zbx-web-service.local:10053/report"