apiVersion: v1
kind: ConfigMap
metadata:
  name: xpipe-v1-web-portal-config
  namespace: xpipe-dorjecurreli
data:
  XPIPE_CORE_ECOMMERCE_CDN_STATIC: "https://cdn-static-cloud-xpipe-v1-web-portal.sindria.org"
  XPIPE_CORE_ECOMMERCE_CDN_MEDIA: "https://cdn-media-cloud-xpipe-v1-web-portal.sindria.org"
  # Core envs
  CORE_PRODUCT_NAME: "XPipe"
  CORE_PRODUCT_VERSION: "1.0"
  CORE_STOREVIEW_ITALIAN_TOGGLE: "1"
  # Fnd envs
  FND_COLLECTOR_BASE_URL: "http://172.16.10.100"
  # Iam envs
  IAM_COLLECTOR_BASE_URL: "http://172.16.10.101"
  # Pipelines envs
  PIPELINES_COLLECTOR_BASE_URL: "http://172.16.10.102"
  # Lab envs
  LAB_COLLECTOR_BASE_URL: "http://172.16.10.103"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xpipe-v1-web-portal-media-config
  namespace: xpipe-dorjecurreli
data:
  AWS_DEFAULT_REGION: "eu-central-1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xpipe-v1-web-portal-backup-config
  namespace: xpipe-dorjecurreli
data:
  AWS_DEFAULT_REGION: "eu-central-1"
  APP_NAME: "xpipe-v1-web-portal"
  RESTORE_TAG: "latest"
  RESTORE_SCHEMA: ""