---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xpipe-v1-web-portal
  name: xpipe-v1-web-portal
  namespace: xpipe-dorjecurreli
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xpipe-v1-web-portal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xpipe-v1-web-portal
    spec:
      imagePullSecrets:
      - name: sindria-dockerhub
      initContainers:
        - name: init-static
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /var/www/app/pub/static" ]
          volumeMounts:
            - mountPath: /var/www/app/pub/static
              name: xpipe-v1-web-portal-static-volume
        - name: init-media
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /var/www/app/pub/media" ]
          volumeMounts:
            - mountPath: /var/www/app/pub/media
              name: xpipe-v1-web-portal-media-volume
        - name: init-generated
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /var/www/app/generated" ]
          volumeMounts:
            - mountPath: /var/www/app/generated
              name: xpipe-v1-web-portal-generated-volume
        - name: init-var
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /var/www/app/var" ]
          volumeMounts:
            - mountPath: /var/www/app/var
              name: xpipe-v1-web-portal-var-volume
      containers:
      - env:
        - name: XPIPE_CORE_ECOMMERCE_CDN_STATIC
          valueFrom:
            configMapKeyRef:
              key: XPIPE_CORE_ECOMMERCE_CDN_STATIC
              name: xpipe-v1-web-portal-config
        - name: XPIPE_CORE_ECOMMERCE_CDN_MEDIA
          valueFrom:
            configMapKeyRef:
              key: XPIPE_CORE_ECOMMERCE_CDN_MEDIA
              name: xpipe-v1-web-portal-config

        - name: CORE_PRODUCT_NAME
          valueFrom:
            configMapKeyRef:
              key: CORE_PRODUCT_NAME
              name: xpipe-v1-web-portal-config
        - name: CORE_PRODUCT_VERSION
          valueFrom:
            configMapKeyRef:
              key: CORE_PRODUCT_VERSION
              name: xpipe-v1-web-portal-config
        - name: CORE_STOREVIEW_ITALIAN_TOGGLE
          valueFrom:
            configMapKeyRef:
              key: CORE_STOREVIEW_ITALIAN_TOGGLE
              name: xpipe-v1-web-portal-config
        - name: CORE_NOTIFICATIONS_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: CORE_NOTIFICATIONS_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config
        - name: CORE_GITHUB_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: CORE_GITHUB_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config




        - name: FND_COLLECTOR_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: FND_COLLECTOR_BASE_URL
              name: xpipe-v1-web-portal-config
        - name: FND_COLLECTOR_ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              key: FND_COLLECTOR_ADMIN_USERNAME
              name: xpipe-v1-web-portal-config
        - name: FND_COLLECTOR_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: FND_COLLECTOR_ADMIN_PASSWORD
              name: xpipe-v1-web-portal-config
        - name: FND_NOTIFICATIONS_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: FND_NOTIFICATIONS_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config
        - name: FND_IDENTITY_SERVER_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: FND_IDENTITY_SERVER_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config
        - name: FND_GATEWAY_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: FND_GATEWAY_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config



        - name: IAM_COLLECTOR_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: IAM_COLLECTOR_BASE_URL
              name: xpipe-v1-web-portal-config
        - name: IAM_COLLECTOR_ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              key: IAM_COLLECTOR_ADMIN_USERNAME
              name: xpipe-v1-web-portal-config
        - name: IAM_COLLECTOR_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: IAM_COLLECTOR_ADMIN_PASSWORD
              name: xpipe-v1-web-portal-config
        - name: IAM_USERS_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: IAM_USERS_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config
        - name: IAM_USERS_META_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: IAM_USERS_META_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config
        - name: IAM_GROUPS_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: IAM_GROUPS_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config
        - name: IAM_POLICIES_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: IAM_POLICIES_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config





        - name: PIPELINES_COLLECTOR_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: PIPELINES_COLLECTOR_BASE_URL
              name: xpipe-v1-web-portal-config
        - name: PIPELINES_COLLECTOR_ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              key: PIPELINES_COLLECTOR_ADMIN_USERNAME
              name: xpipe-v1-web-portal-config
        - name: PIPELINES_COLLECTOR_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: PIPELINES_COLLECTOR_ADMIN_PASSWORD
              name: xpipe-v1-web-portal-config
        - name: PIPELINES_CONFIGMAP_VAULT_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: PIPELINES_CONFIGMAP_VAULT_BASE_URL
              name: xpipe-v1-web-portal-config
        - name: PIPELINES_CONFIGMAP_VAULT_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: PIPELINES_CONFIGMAP_VAULT_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config
        - name: PIPELINES_TEMPLATE_CATALOG_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: PIPELINES_TEMPLATE_CATALOG_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config
        - name: PIPELINES_ORCHESTRATOR_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: PIPELINES_ORCHESTRATOR_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config





        - name: LAB_COLLECTOR_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: LAB_COLLECTOR_BASE_URL
              name: xpipe-v1-web-portal-config
        - name: LAB_COLLECTOR_ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              key: LAB_COLLECTOR_ADMIN_USERNAME
              name: xpipe-v1-web-portal-config
        - name: LAB_COLLECTOR_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: LAB_COLLECTOR_ADMIN_PASSWORD
              name: xpipe-v1-web-portal-config
        - name: LAB_CONFIGMAP_VAULT_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: LAB_CONFIGMAP_VAULT_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config
        - name: LAB_SHELL_CATALOG_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: LAB_SHELL_CATALOG_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config
        - name: LAB_ORCHESTRATOR_ACCESS_TOKEN
          valueFrom:
            configMapKeyRef:
              key: LAB_ORCHESTRATOR_ACCESS_TOKEN
              name: xpipe-v1-web-portal-config




        - name: XPIPE_CORE_AUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: XPIPE_CORE_AUTH_CLIENT_ID
              name: xpipe-v1-web-portal-secret
        - name: XPIPE_CORE_AUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: XPIPE_CORE_AUTH_CLIENT_SECRET
              name: xpipe-v1-web-portal-secret
        - name: XPIPE_CORE_ECOMMERCE_DB_HOST
          valueFrom:
            secretKeyRef:
              key: XPIPE_CORE_ECOMMERCE_DB_HOST
              name: xpipe-v1-web-portal-secret
        - name: XPIPE_CORE_ECOMMERCE_DB_DATABASE
          valueFrom:
            secretKeyRef:
              key: XPIPE_CORE_ECOMMERCE_DB_DATABASE
              name: xpipe-v1-web-portal-secret
        - name: XPIPE_CORE_ECOMMERCE_DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: XPIPE_CORE_ECOMMERCE_DB_USERNAME
              name: xpipe-v1-web-portal-secret
        - name: XPIPE_CORE_ECOMMERCE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: XPIPE_CORE_ECOMMERCE_DB_PASSWORD
              name: xpipe-v1-web-portal-secret
        - name: XPIPE_CORE_ECOMMERCE_CRYPT_KEY
          valueFrom:
            secretKeyRef:
              key: XPIPE_CORE_ECOMMERCE_CRYPT_KEY
              name: xpipe-v1-web-portal-secret
        image: sindriainc/nginx-php:7.1.0-local-magento-7.4
        imagePullPolicy: Always
        #securityContext:
        #  capabilities:
        #    add:
        #      - NET_ADMIN
        #livenessProbe:
        #  failureThreshold: 3
        #  httpGet:
        #    path: /afc/channelactivity/actuator/health
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 50
        #  periodSeconds: 10
        #  successThreshold: 1
        #  timeoutSeconds: 1
        name: xpipe-v1-web-portal
        ports:
        - containerPort: 80
          protocol: TCP
        #readinessProbe:
        #  failureThreshold: 3
        #  httpGet:
        #    path: /afc/channelactivity/actuator/health
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 20
        #  periodSeconds: 10
        #  successThreshold: 1
        #  timeoutSeconds: 1
        resources:
          limits:
            memory: 8192Mi
          requests:
            memory: 8192Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/app/pub/static
          name: xpipe-v1-web-portal-static-volume
        - mountPath: /var/www/app/pub/media
          name: xpipe-v1-web-portal-media-volume
        - mountPath: /var/www/app/generated
          name: xpipe-v1-web-portal-generated-volume
        - mountPath: /var/www/app/var
          name: xpipe-v1-web-portal-var-volume
      dnsPolicy: ClusterFirst
      #hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: xpipe-v1-web-portal-static-volume
        persistentVolumeClaim:
          claimName: xpipe-v1-web-portal-static-pvc
          #defaultMode: 420
      - name: xpipe-v1-web-portal-media-volume
        persistentVolumeClaim:
          claimName: xpipe-v1-web-portal-media-pvc
          #defaultMode: 420
      - name: xpipe-v1-web-portal-generated-volume
        persistentVolumeClaim:
          claimName: xpipe-v1-web-portal-generated-pvc
          #defaultMode: 420
      - name: xpipe-v1-web-portal-var-volume
        persistentVolumeClaim:
          claimName: xpipe-v1-web-portal-var-pvc
          #defaultMode: 420
---
