apiVersion: batch/v1
kind: Job
metadata:
  name: magento-post-deploy
  namespace: xpipe-dorjecurreli
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: magento-cli
        image: sindriaproject/xpipe-v1-web-portal:@@RELEASE_VERSION@@
        command:
          - sh
          - -c
          - |
            php bin/magento setup:upgrade && php bin/magento setup:static-content:deploy it_IT en_US -f && php bin/magento setup:di:compile && php bin/magento cache:flush && echo "Magento post-deploy complete"
        envFrom:
        - configMapRef:
            name: xpipe-v1-web-portal-config
        - secretRef:
            name: xpipe-v1-web-portal-secret
        volumeMounts:
        - mountPath: /var/www/app/pub/static
          name: xpipe-v1-web-portal-static-volume
        - mountPath: /var/www/app/pub/media
          name: xpipe-v1-web-portal-media-volume
        - mountPath: /var/www/app/generated
          name: xpipe-v1-web-portal-generated-volume
        - mountPath: /var/www/app/var
          name: xpipe-v1-web-portal-var-volume
      volumes:
      - name: xpipe-v1-web-portal-static-volume
        persistentVolumeClaim:
          claimName: xpipe-v1-web-portal-static-pvc
      - name: xpipe-v1-web-portal-media-volume
        persistentVolumeClaim:
          claimName: xpipe-v1-web-portal-media-pvc
      - name: xpipe-v1-web-portal-generated-volume
        persistentVolumeClaim:
          claimName: xpipe-v1-web-portal-generated-pvc
      - name: xpipe-v1-web-portal-var-volume
        persistentVolumeClaim:
          claimName: xpipe-v1-web-portal-var-pvc
