apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: xpipe-policies-secret
  namespace: xpipe-demo
stringData:
  XPIPE_CORE_POLICIES_DB_CONNECTION_URL: "jdbc:mysql://xpipe-policies-db.xpipe-demo.svc.cluster.local:3306/app?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false"
  XPIPE_CORE_POLICIES_DB_USERNAME: "root"
  XPIPE_CORE_POLICIES_DB_PASSWORD: "secret"
