---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xpipe-policies
  name: xpipe-policies
  namespace: xpipe-demo
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: xpipe-policies
  sessionAffinity: None
  type: ClusterIP