apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelines-v1-rst-configmapvault-config
  namespace: xpipe-cloud
data:
  VAULT_LOG_LEVEL: "info"
  VAULT_UI: "true"
  VAULT_ADDR: "https://configmap-vault-xpipe.sindria.org"
  VAULT_API_ADDRESS: "https://configmap-vault-xpipe.sindria.org"
  VAULT_DISABLE_MLOCK: "true"
  VAULT_MYSQL_PLAINTEXT_CONNECTION_ALLOWED: "true"
  VAULT_TLS_DISABLE: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelines-v1-rst-configmapvault-backup-config
  namespace: xpipe-cloud
data:
  AWS_DEFAULT_REGION: "eu-central-1"
  APP_NAME: "pipelines-v1-rst-configmapvault"
  RESTORE_TAG: "latest"
  RESTORE_SCHEMA: ""