---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipelines-v1-rst-configmapvault
  name: pipelines-v1-rst-configmapvault
  namespace: xpipe-cloud
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pipelines-v1-rst-configmapvault
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pipelines-v1-rst-configmapvault
    spec:
      imagePullSecrets:
      - name: sindria-dockerhub
      initContainers:
        - name: init-lostfound
          image: busybox
          command: [ "sh", "-c", "rm -Rf /vault/data/lost+found" ]
          volumeMounts:
            - mountPath: /vault/data
              name: pipelines-v1-rst-configmapvault-data-volume
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
        - name: init-data
          image: busybox
          command: [ "sh", "-c", "chown -R 100:1000 /vault/data" ]
          volumeMounts:
            - mountPath: /vault/data
              name: pipelines-v1-rst-configmapvault-data-volume
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
      containers:
      - env:
        - name: VAULT_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              key: VAULT_LOG_LEVEL
              name: pipelines-v1-rst-configmapvault-config
        - name: VAULT_UI
          valueFrom:
            configMapKeyRef:
              key: VAULT_UI
              name: pipelines-v1-rst-configmapvault-config
        - name: VAULT_ADDR
          valueFrom:
            configMapKeyRef:
              key: VAULT_ADDR
              name: pipelines-v1-rst-configmapvault-config
        - name: VAULT_API_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: VAULT_API_ADDRESS
              name: pipelines-v1-rst-configmapvault-config
        - name: VAULT_DISABLE_MLOCK
          valueFrom:
            configMapKeyRef:
              key: VAULT_DISABLE_MLOCK
              name: pipelines-v1-rst-configmapvault-config
        - name: VAULT_MYSQL_PLAINTEXT_CONNECTION_ALLOWED
          valueFrom:
            configMapKeyRef:
              key: VAULT_MYSQL_PLAINTEXT_CONNECTION_ALLOWED
              name: pipelines-v1-rst-configmapvault-config
        - name: VAULT_TLS_DISABLE
          valueFrom:
            configMapKeyRef:
              key: VAULT_TLS_DISABLE
              name: pipelines-v1-rst-configmapvault-config
        - name: VAULT_MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              key: VAULT_MYSQL_USERNAME
              name: pipelines-v1-rst-configmapvault-secret
        - name: VAULT_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: VAULT_MYSQL_PASSWORD
              name: pipelines-v1-rst-configmapvault-secret
        - name: VAULT_MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: VAULT_MYSQL_DATABASE
              name: pipelines-v1-rst-configmapvault-secret
        - name: VAULT_MYSQL_ADDRESS
          valueFrom:
            secretKeyRef:
              key: VAULT_MYSQL_ADDRESS
              name: pipelines-v1-rst-configmapvault-secret
        image: sindriainc/vault:2.0.0-1.17.3
        imagePullPolicy: Always
        #command: [ "tail" ]
        #args: [ "-f", "/dev/null" ]
        #command: [ "vault" ]
        #args: [ "server", "-config", "/vault/config/config.hcl" ]
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        #lifecycle:
        #  postStart:
        #    exec:
        #      command: [ "/bin/sh", "-c", "/post_start.sh", "${VAULT_API_ADDRESS}" ]
        #      #command: [ "vault", "operator", "init", "-address=https://sindria-vault-xpipe.sindria.org", "-key-shares=5", "-key-threshold=2 > /vault/data/keys.txt" ]
        #      # vault operator init -address=https://sindria-vault-xpipe.sindria.org -key-shares=5 -key-threshold=2 > /vault/data/keys.txt
        #livenessProbe:
        #  failureThreshold: 3
        #  httpGet:
        #    path: /afc/channelactivity/actuator/health
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 50
        #  periodSeconds: 10
        #  successThreshold: 1
        #  timeoutSeconds: 1
        name: pipelines-v1-rst-configmapvault
        ports:
        - containerPort: 8200
          protocol: TCP
        - containerPort: 8201
          protocol: TCP
        #readinessProbe:
        #  failureThreshold: 3
        #  httpGet:
        #    path: /afc/channelactivity/actuator/health
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 20
        #  periodSeconds: 10
        #  successThreshold: 1
        #  timeoutSeconds: 1
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 1024Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /vault/data
          name: pipelines-v1-rst-configmapvault-data-volume
        #- mountPath: /vault/config/config.hcl
        #  name: pipelines-v1-rst-configmapvault-config-volume
        #  subPath: config.hcl
      dnsPolicy: ClusterFirst
      #hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: pipelines-v1-rst-configmapvault-data-volume
        persistentVolumeClaim:
          claimName: pipelines-v1-rst-configmapvault-data-pvc
          #defaultMode: 420
      #- name: pipelines-v1-rst-configmapvault-config-volume
      #  configMap:
      #    name: pipelines-v1-rst-configmapvault-config
---
