---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pipelines-v1-rst-configmapvault
  name: pipelines-v1-rst-configmapvault-data-pvc
  namespace: xpipe-cloud
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi