---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipelines-v1-rst-configmapvault
  name: pipelines-v1-rst-configmapvault
  namespace: xpipe-cloud
spec:
  ports:
  - name: web
    port: 8200
    protocol: TCP
    targetPort: 8200
  - name: cluster
    port: 8201
    protocol: TCP
    targetPort: 8201
  selector:
    app: pipelines-v1-rst-configmapvault
  sessionAffinity: None
  type: ClusterIP