stages:
  - test
  - build
  - push
  - deploy

.set_colors: &set_colors
  - export BLUE='\033[0;34m'
  - export YELLOW='\033[0;33m'
  - export RED='\033[0;31m'
  - export NC='\033[0m' #No Color
  - export NOW=$(date "+%Y-%m-%d_%H-%M-%S")
  
.setup_storage: &setup_storage
  - ssh $SERVER "mkdir -p $BASE_PATH/$IMAGE_NAME"
  - ssh $SERVER "mkdir -p $BASE_PATH/$IMAGE_NAME/storage"
  - ssh $SERVER "mkdir -p $BASE_PATH/$IMAGE_NAME/storage/data"
  - ssh $SERVER "mkdir -p $BASE_PATH/$IMAGE_NAME/storage/logs"

variables:
  BASE_PATH: "/home/sindria"
  IMAGE_NAMESPACE: "registry.sindria.org/example-team"
  IMAGE_NAME: "example-service"
  SERVER: "example.sindria.org"
  PHP_VERSION: "7.4"
  NODEJS_VERSION: "10"

build:composer:
  image: sindriainc/nginx-php:1.5.0-$PHP_VERSION-local
  stage: .pre
  tags:
    - default
  only:
    - tags
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - src/vendor/
      - src/.env
      - src/storage/
  script:
    - echo -e "${BLUE}Building...${NC}"
    - cd src
    - composer install --no-interaction --no-suggest --no-ansi --no-progress
    - echo #
    - echo -e "${BLUE}Installing...${NC}"
    - cp .env.production .env
  artifacts:
    paths:
      - src/vendor/
      - src/.env
      - src/storage/
    expire_in: 7 days

build:assets:
  image: sindriainc/nodejs:1.2.0-$NODEJS_VERSION
  stage: .pre
  tags:
    - default
  only:
    - tags
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - src/node_modules/
      - src/public/
  script:
    - echo -e "${BLUE}Installing dependencies...${NC}"
    - cd src
    - npm install
    - echo #
    - echo -e "${BLUE}Building...${NC}"
    - npm run production
  artifacts:
    paths:
      - src/node_modules/
      - src/public/
    expire_in: 7 days

test:app:
  image: sindriainc/nginx-php:1.5.0-$PHP_VERSION-local
  stage: test
  when: manual
  services:
    - name: mariadb:10.4
      alias: database
  variables:
    MYSQL_DATABASE: "app_test"
    MYSQL_ROOT_PASSWORD: "root"
  only:
    - tags
    - branches
  before_script:
    - *set_colors
    - cp .env.example .env
  script:
    - vendor/bin/phpunit --configuration phpunit-ci.xml

build:docker:
  image: registry.sindria.org/devops/base-images/image-builder:latest
  stage: build
  tags:
    - docker
  only:
    - tags
  before_script:
    - *set_colors
  script:
    - echo -e "${BLUE}Building image...${NC}"
    - bash build.sh $IMAGE_NAMESPACE/$IMAGE_NAME $CI_COMMIT_TAG
    - cowsay -f tux "Build Success"

push:docker:
  image: registry.sindria.org/devops/base-images/image-builder:latest
  stage: push
  tags:
    - docker
  only:
    - tags
  before_script:
    - *set_colors
  script:
    - echo -e "${BLUE}Pushing image into registry...${NC}"
    - docker push $IMAGE_NAMESPACE/$IMAGE_NAME:$CI_COMMIT_TAG
    - docker push $IMAGE_NAMESPACE/$IMAGE_NAME:latest
    - echo #
    - echo -e "${BLUE}Cleaning local registry...${NC}"
    - docker image rm $IMAGE_NAMESPACE/$IMAGE_NAME:$CI_COMMIT_TAG
    - docker image rm $IMAGE_NAMESPACE/$IMAGE_NAME:latest
    - echo #
    - cowsay -f dragon "Well Done! New docker image is now on your registry."

deploy:app:
  image: registry.sindria.org/devops/base-images/deployer:latest
  stage: deploy
  tags:
    - default
  only:
    - tags
  before_script:
    - *set_colors
    - cp .env.production .env
    - cp docker-compose.production.yml docker-compose.yml
  script:
    - *setup_storage
    - ssh $SERVER "docker stop $IMAGE_NAME" || echo -e "${YELLOW}No such container $IMAGE_NAME${NC}"
    - ssh $SERVER "docker rm $IMAGE_NAME" || echo -e "${YELLOW}No such container $IMAGE_NAME${NC}"
    - rsync -ravP -e "ssh" --exclude='.git' --exclude='.git*' --exclude='.gitlab-ci.yml' --exclude='readme.md' --exclude='README.md' --exclude='build.sh' --exclude='storage' --exclude='src' --exclude='certs' --exclude='docker-compose.local.yml' --exclude='docker-compose.production.yml' --exclude='.env.local' --exclude='.env.production' --delete $CI_PROJECT_DIR/ $SERVER:/$BASE_PATH/$IMAGE_NAME/
    - ssh $SERVER "sudo chmod 770 $BASE_PATH/$IMAGE_NAME"
    - ssh $SERVER "docker image rm $IMAGE_NAMESPACE/$IMAGE_NAME:latest" || echo -e "${YELLOW}Image not present into this local registry${NC}"
    - ssh $SERVER "cd $BASE_PATH/$IMAGE_NAME; docker-compose up -d"
    - cowsay "Deploy Success"