<?php
/**
 * Copyright © Sindria, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block
 */
//dd($block);

$beta = $block->getIndividualProduct();
$pro = $block->getProProduct();
$enterprise = $block->getEnterpriseProduct();
//dd($pro);

//$productCollection = $block->getProductCollection();
////dd($productCollection);
//foreach ($productCollection as $product) {
//
//    dump($product);
//    //print_r($product->getData());
//    echo "<br>";
//}

?>

<!--<h1>--><?php //echo $block->escapeHtml($block->getWelcomeText()) ?><!--</h1>-->

<!-------------- Hero section starts --------------->
<header>
    <div class="container">
<!--        <img src="--><?php //echo $this->getViewFileUrl('Pipe_LandingPage::images/logo-small.png'); ?><!--" alt="" class="logo">-->
<!--        <span>XPipe</span>-->

<!--        <img src="--><?php //echo $this->getViewFileUrl('Pipe_LandingPage::images/hero-bg.png'); ?><!--" alt="" class="hero-bg">-->

        <div class="row">
            <div class="col hero-content">
                <h2 class="main-heading">
                    All of your work in one place.
                </h2>
                <h3 class="sub-heading">
                    Organizes work so teams know what to do, and how to get it done.
                </h3>
                <div class="inner-row">
                    <div class="col">
                        <button class="btn btn-filled">
                            <a href="<?= $beta->getProductUrl() ?>"><?= __("Let's get started") ?></a>
                        </button>
                    </div>
                    <div class="col">
                        <button class="btn btn-empty">
                            <a href="#">
                                Watch video <ion-icon name="play-circle-outline"></ion-icon>
                            </a>
                        </button>
                    </div>
                </div>
            </div>
            <div class="col hero-img">
                <img src="<?php echo $this->getViewFileUrl('Pipe_LandingPage::images/saas-thumbnail.jpg'); ?>" alt="" class="featured-img">
            </div>
        </div>
    </div>
</header>
<!-------------- Hero section starts --------------->


<!-------------- projects section starts --------------->
<section class="projects saas-info">
    <div class="container">
        <div class="row">
            <div class="col saas-img-wrap">
                <img src="<?php echo $this->getViewFileUrl('Pipe_LandingPage::images/saas-project.jpg'); ?>" alt="" class="saas-screen">
            </div>
            <div class="col">
                <h2 class="heading">
                    Stay organized and connected.
                </h2>
                <p class="para-line">
                    Id eu ac aenean nibh orci orci phasellus cras cursus arcu ullamcorper turpis praesent elementum tortor quis ultrices ut sed quis sollicitudin feugiat vitae.
                </p>
                <div class="inner-row">
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Organize and assign task
                        </h5>
                    </div>
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Create plan your team can count on
                        </h5>
                    </div>
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Make it easy to focus
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-------------- projects section ends --------------->


<!-------------- Process section starts -------------->
<section class="process saas-info">
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class="heading">
                    Choose a workflow or make your own.
                </h2>
                <p class="para-line">
                    Id eu ac aenean nibh orci orci phasellus cras cursus arcu ullamcorper turpis praesent elementum tortor quis ultrices ut sed quis sollicitudin feugiat vitae.
                </p>
                <div class="inner-row">
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Product development
                        </h5>
                    </div>
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Sales & CRM
                        </h5>
                    </div>
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Marketing
                        </h5>
                    </div>
                </div>
            </div>
            <div class="col saas-img-wrap">
                <img src="<?php echo $this->getViewFileUrl('Pipe_LandingPage::images/saas-process.png'); ?>" alt="" class="saas-screen">
            </div>
        </div>
    </div>
</section>
<!-------------- Process section ends -------------->


<!-------------- Automation section starts ------------>
<section class="automation saas-info">
    <div class="container">
        <div class="row">
            <div class="col saas-img-wrap">
                <img src="<?php echo $this->getViewFileUrl('Pipe_LandingPage::images/saas-automation.png'); ?>" alt="" class="saas-screen">
            </div>
            <div class="col">
                <h2 class="heading">
                    Automating routine work. Save time.
                </h2>
                <p class="para-line">
                    Id eu ac aenean nibh orci orci phasellus cras cursus arcu ullamcorper turpis praesent elementum tortor quis ultrices ut sed quis sollicitudin feugiat vitae.
                </p>
                <div class="inner-row hero-btn-row">
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Auto assigne
                        </h5>
                    </div>
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Notify team member
                        </h5>
                    </div>
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Integrating app
                        </h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-------------- Automation section ends ------------>


<!-------------- Integration section starts ----------->
<section class="integration saas-info">
    <div class="container">
        <div class="row">
            <div class="col">
                <h2 class="heading">
                    Integrate with tools you already use.
                </h2>
                <p class="para-line">
                    Id eu ac aenean nibh orci orci phasellus cras cursus arcu ullamcorper turpis praesent elementum tortor quis ultrices ut sed quis sollicitudin feugiat vitae.
                </p>
                <div class="inner-row">
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Knowledge management
                        </h5>
                    </div>
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Development workflow
                        </h5>
                    </div>
                    <div class="project-featured-list">
                        <ion-icon name="checkmark-circle-outline"></ion-icon>
                        <h5 class="list-name">
                            Continuous integration
                        </h5>
                    </div>
                </div>
            </div>
            <div class="col saas-img-wrap">
                <img src="<?php echo $this->getViewFileUrl('Pipe_LandingPage::images/saas-integration.png'); ?>" alt="" class="saas-screen">
            </div>
        </div>
    </div>
</section>
<!-------------- Integration section ends ----------->


<!-------------- CTA section starts --------------->
<!--<section class="cta">-->
<!--    <div class="container">-->
<!--        <button class="btn btn-filled">-->
<!--            <a href="#">Let's get started</a>-->
<!--        </button>-->
<!--    </div>-->
<!--</section>-->
<!-------------- CTA section ends --------------->


<!--------------- Featured review section start -------------->
<!--<section class="featured-review">-->
<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col featured-author-col">-->
<!--                <img src="--><?php //echo $this->getViewFileUrl('Pipe_LandingPage::images/featured-testimonial-author.jpg'); ?><!--" class="featured-author" alt="Features Author">-->
<!--            </div>-->
<!--            <div class="col featured-review-content">-->
<!--                <ion-icon name="attach-outline"></ion-icon>-->
<!---->
<!--                <p class="review">-->
<!--                    I cannot stress how important it is to have all of our information in one central place. We use XPipe to vestibulum mi malesuada scelerisque et bibendum sapien vivamus ac.-->
<!--                </p>-->
<!---->
<!--                <p class="author-name">-->
<!--                    Julia Keys — Associate Director at Luca-->
<!--                </p>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</section>-->
<!--------------- Featured review section end -------------->


<!--------------- Plan section starts ------------------->
<section class="plan">
    <div class="container">
        <h2 class="heading">
            Simple plan. <br>
            Supercharge your teamwork.
        </h2>
        <p class="para-line">
            Get the power, control, and customization you need to manage <br>your team’s and organization’s projects.
        </p>
        <div class="row plans">
            <div class="single-plan free">
                <h3 class="plan-name"><?= $beta->getName() ?></h3>
                <p class="plan-detail">
                    <?= $beta->getMetaDescription() ?>
                </p>
                <h1 class="plan-value">
                    <?php
                    $exploded = explode('.', $beta->getPrice());
                    $firstValue = (int) $exploded[0];
                    $value = ($firstValue == false) ? "Free" : $beta->getPrice();
                    echo $value;


                    ?>
                    <?php // $block->getFormattedPrice($beta->getPrice()) ?> <!-- <em>/year</em> -->
                </h1>
                <button class="btn btn-bordered">
                    <a href="<?= $beta->getProductUrl() ?>"><?= __("Let's get started") ?></a>
                </button>

                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Pipelines Templates
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Xdev Cloud
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; ChatOps
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; VoiceOps
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Docs
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Envs Setup
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Development Tools
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Up to 3 concurrent pipelines
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Single user
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Basic Support
                </p>
            </div>

            <div class="single-plan basic">
                <p class="highlighter">Best seller!</p>
                <h3 class="plan-name"><?= $pro->getName() ?></h3>
                <p class="plan-detail">
                    <?= $pro->getMetaDescription() ?>
                </p>
                <h1 class="plan-value">
                    <?= $block->getFormattedPrice($pro->getPrice()) ?> <em>/year</em>
                </h1>
                <button class="btn btn-filled btn-shadow">
                    <a href="<?= $pro->getProductUrl() ?>">
                        <?= __("Let's get started") ?>
                    </a>
                </button>

                <h6 class="feature-heading">Everything in Individual, plus:</h6>

                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; IAM
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Dedicated Xdev Cloud
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Up to 10 concurrent pipelines
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Up to 30 users
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Pro Support
                </p>
            </div>

            <div class="single-plan unlimited">
                <h3 class="plan-name"><?= $enterprise->getName() ?></h3>
                <p class="plan-detail">
                    <?= $enterprise->getMetaDescription() ?>
                </p>
                <h1 class="plan-value">
                    <?php // $block->getFormattedPrice($enterprise->getPrice()) ?> <!-- <em>/year</em> -->
                    <?= __("Contact Us") ?>
                </h1>
                <button class="btn btn-bordered btn-hover">
                    <a href="<?= $this->getBaseUrl() . 'contact' ?>"><?= __("Let's get started") ?></a>
                </button>

                <h6 class="feature-heading">Everything in Individual and Pro, plus:</h6>

                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; IAM SAAS
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Up to 20 concurrent pipelines
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Up to 100 users
                </p>
                <p class="plan-feature">
                    <ion-icon name="checkbox-outline"></ion-icon>
                    &nbsp; Enterprise Support
                </p>
            </div>
        </div>
    </div>
</section>
<!--------------- Plan section ends ------------------->


<!--------------- Saas category section starts --------------->
<div class="saas-category">
    <div class="container">
        <h2 class="heading white">
            One workspace. <br>
            Best for a busy worker like you.
        </h2>

        <div class="row saas-categories">
            <div class="col">
                <ion-icon name="person-outline"></ion-icon>
                <h4 class="category-name">Freelancer</h4>
                <p class="detail">
                    Egestas hendrerit tincidunt massa nunc mattis non iaculis sed egestas
                </p>
            </div>
            <div class="col">
                <ion-icon name="briefcase-outline"></ion-icon>
                <h4 class="category-name">Agencies</h4>
                <p class="detail">
                    Egestas hendrerit tincidunt massa nunc mattis non iaculis sed egestas
                </p>
            </div>
            <div class="col">
                <ion-icon name="prism-outline"></ion-icon>
                <h4 class="category-name">Enterprise</h4>
                <p class="detail">
                    Egestas hendrerit tincidunt massa nunc mattis non iaculis sed egestas
                </p>
            </div>
        </div>

        <span>
				<button class="btn btn-filled-white">
					<a href="<?= $beta->getProductUrl() ?>">
						<?= __("Let's get started") ?>
					</a>
				</button>
			</span>
    </div>
</div>
<!--------------- Saas category section starts --------------->


<!--------------- FAQ section started ------------------->
<section class="faq">
    <div class="container">
        <h2 class="heading">
            Frequently asked questions
        </h2>

        <div class="row faqs">
            <div class="col">
                <h3 class="question">
                    Is there a free version of XPipe?
                </h3>
                <p class="para-line answer">
                    Tincidunt morbi amet rhoncus risus non ut at amet, molestie scelerisque consequat porta ullamcorper habitant elementum lacinia lectus adipiscing donec.
                </p>
                <hr>
            </div>
            <div class="col">
                <h3 class="question">
                    Which pricing plan is right for me?
                </h3>
                <p class="para-line answer">
                    Mollis nibh tristique molestie massa ultricies nunc, nunc vitae, cras ornare odio imperdiet eros scelerisque urna eget vitae nulla volutpat erat risus magna nisi.
                </p>
                <hr>
            </div>
        </div>

        <div class="row faqs">
            <div class="col">
                <h3 class="question">
                    How much does it cost?
                </h3>
                <p class="para-line answer">
                    Massa adipiscing id massa magna quam nec adipiscing nunc tristique tincidunt duis amet nunc, tellus, in magna elit ut neque volutpat.
                </p>
                <hr>
            </div>
            <div class="col">
                <h3 class="question">
                    How does our pricing work?
                </h3>
                <p class="para-line answer">
                    Nullam pulvinar nisl lorem quis nec turpis congue arcu tristique leo quam eget lorem fusce rhoncus lorem mauris, porta sit.
                </p>
                <hr>
            </div>
        </div>

        <div class="row faqs">
            <div class="col">
                <h3 class="question">
                    Can you pay for XPipe monthly?
                </h3>
                <p class="para-line answer">
                    Venenatis purus, leo, ac sapien tempus diam tellus in aenean turpis nibh aenean augue mauris nulla eu, quis amet, semper eu amet nisl tellus.
                </p>
                <hr>
            </div>
            <div class="col">
                <h3 class="question">
                    What if I change my mind?
                </h3>
                <p class="para-line answer">
                    Mollis nibh tristique molestie massa ultricies nunc, nunc vitae, cras ornare odio imperdiet eros scelerisque urna eget vitae nulla volutpat erat risus magna nisi
                </p>
                <hr>
            </div>
        </div>

        <div class="row faqs">
            <div class="col">
                <h3 class="question">
                    Does XPipe offer plans for students?
                </h3>
                <p class="para-line answer">
                    Viverra vestibulum, nibh elit nisl in ultrices turpis egestas maecenas ut sit ut neque massa tortor in ultricies sem dictum.
                </p>
                <hr>
            </div>
            <div class="col">
                <h3 class="question">
                    What payment methods do you accept?
                </h3>
                <p class="para-line answer">
                    Feugiat velit sit enim ipsum, morbi viverra euismod in nunc feugiat consequat placerat magna etiam lorem a ut lectus dignissim.
                </p>
                <hr>
            </div>
        </div>
    </div>
</section>
<!--------------- FAQ section end ------------------->
