<?php
/**
 * Copyright © Sindria, Inc. All rights reserved.
 * See LICENSE for license details.
 */

/** @var $block \Magento\Backend\Block\Page\Header */
$part = $block->getShowPart();
?>
<?php if ($part === 'logo') : ?>
    <?php $edition = $block->hasEdition() ? 'data-edition="' . $block->escapeHtml($block->getEdition()) . '"' : ''; ?>
    <?php $logoSrc = ($block->hasLogoImageSrc()) ? $block->escapeHtml($block->getLogoImageSrc()) : 'images/magento-logo.svg' ?>
    <a
        href="<?= $block->escapeUrl($block->getHomeLink()) ?>"
        <?= /* @noEscape */ $edition ?>
        class="logo">
        <img class="logo-img" src="<?= /* @noEscape */ $block->getViewFileUrl($logoSrc) ?>"
             alt="<?= $block->escapeHtml(__('XPipe Dashboard')) ?>" title="<?= $block->escapeHtml(__('XPipe Dashboard')) ?>"/>
    </a>
<?php endif; ?>
