---
version: 0.1.0
routes:
  - route:
      name: "api.v1.policies"
      isPublic: false
      version: v1
      context: policies
      method: GET
      uri: "/"
      comment: "Get all policies"
  - route:
      name: "api.v1.policies.show"
      isPublic: false
      version: v1
      context: policies
      method: GET
      uri: "/show/{id}"
      comment: "Get a policy"
  - route:
      name: "api.v1.policies.search"
      isPublic: false
      version: v1
      context: policies
      method: POST
      uri: "/search"
      comment: "Search policy"
  - route:
      name: "api.v1.policies.store"
      isPublic: false
      version: v1
      context: policies
      method: POST
      uri: "/"
      comment: "Store a policy"
  - route:
      name: "api.v1.policies.edit"
      isPublic: false
      version: v1
      context: policies
      method: PUT
      uri: "/edit"
      comment: "Edit a policy"
  - route:
      name: "api.v1.policies.delete"
      isPublic: false
      version: v1
      context: policies
      method: DELETE
      uri: "/delete/{id}"
      comment: "Delete a policy"
  - route:
      name: "api.v1.policies.showUserPolicies"
      isPublic: false
      version: v1
      context: policies
      method: GET
      uri: "/show/user/{id}"
      comment: "Show policies attached to a user"
  - route:
      name: "api.v1.policies.showPolicyUsers"
      isPublic: false
      version: v1
      context: policies
      method: GET
      uri: "/show/users/{id}"
      comment: "Show users attached to policy"
  - route:
      name: "api.v1.policies.attach"
      isPublic: false
      version: v1
      context: policies
      method: POST
      uri: "/attach"
      comment: "Attach a policy"
  - route:
      name: "api.v1.policies.detach"
      isPublic: false
      version: v1
      context: policies
      method: POST
      uri: "/detach"
      comment: "Detach a policy"