version: '3.7'

services:
  # =app
  app:
    image: "registry.sindria.org/<project-namespace>/<repo-name>:${APP_VERSION}"
    container_name: "${APP_NAME}"
    environment:
      - DEFAULT_SINDRIA_USER_PASSWORD=${DEFAULT_SINDRIA_USER_PASSWORD}
    #volumes:
    #  - "${APP_DATA_PATH}:${APP_CODE_PATH}/storage"
    hostname: "${APP_NAME}.local"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #  vpc_<app-name>:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #     - "${APP_NAME}.local"

  # =db
  #db:
  #  image: "sindriainc/postgres:${POSTGRES_TAG}-${POSTGRES_VERSION}"
  #  #image: "sindriainc/mariadb:${MARIADB_TAG}-${MARIADB_VERSION}"
  #  container_name: "${APP_NAME}-db"
  #  environment:
  #    - POSTGRES_USER=${DB_USERNAME}
  #    - POSTGRES_PASSWORD=${DB_ROOT_PASSWORD}
  #    - POSTGRES_DB=${DB_DATABASE}
  #    #- MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  #    #- MYSQL_DATABASE=${DB_DATABASE}
  #  volumes:
  #    - "${APP_DATA_PATH}/db/:/var/lib/postgresql:delegated"
  #    #- "${APP_DATA_PATH}/db/:/var/lib/mysql:delegated"
  #  hostname: "${APP_NAME}-db.local"
  #  #ports:
  #  #   - "5432:5432"
  #  #   - "3306:3306"
  #  networks:
  #    default:
  #      ipv4_address: "${DB_IP_ADDRESS}"
  #      aliases:
  #        - "${APP_NAME}-db.local"
  #  #networks:
  #  #  vpc_<app-name>:
  #  #    ipv4_address: "${DB_IP_ADDRESS}"
  #  #    aliases:
  #  #      - "${APP_NAME}.local"


# =networks
networks:
  default:
    name: "vpc_${APP_NAME}"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:        
#  vpc_<app-name>:
#    external: true 