version: '3.9'

services:
  # =app
  app:
    image: "sindriainc/kind:${KIND_TAG}"
    container_name: "${APP_NAME}-init"
    command: bash -c "kind create cluster --config /var/www/app/config/cluster-config.yaml; tail -f /dev/null"
    #entrypoint: "tail -f /dev/null"
    volumes:
      - "${BASE_PATH}/${PROJECT_PATH}/${CODE_PATH}:${APP_CODE_PATH}"
      - "/var/run/docker.sock:/var/run/docker.sock"
    hostname: "${APP_NAME}.local"
    #ports:
    #  - "6443:6443"
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    security_opt:
      - seccomp:unconfined
    #networks:
    #  default:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}-init.local"
    #networks:
    #  vpc_<app-name>:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}-init.local"


# =networks
#networks:
#  default:
#    name: "vpc_${APP_NAME}"
#    driver: bridge
#    ipam:
#      config:
#        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_<app-name>:
#    external: true