<?php
namespace Core\SystemEnv\Helper;

class SystemEnvHelper
{
    private const ALLOWED_KEYS = [
        // Core envs
        'CORE_SSO_BASE_URL',
        'CORE_SSO_BASE_URL_LEGACY',
        'CORE_SSO_REALM',
        'CORE_SSO_CLIENT_ID',
        'CORE_SSO_CLIENT_SECRET',
        'CORE_PRODUCT_NAME',
        'CORE_PRODUCT_VERSION',
        'CORE_STOREVIEW_ITALIAN_TOGGLE',
        'CORE_NOTIFICATIONS_ACCESS_TOKEN',
        'CORE_GITHUB_ACCESS_TOKEN',
        'CORE_CONFIG_TENANT',
        // Fnd envs
        'FND_COLLECTOR_BASE_URL',
        'FND_COLLECTOR_ADMIN_USERNAME',
        'FND_COLLECTOR_ADMIN_PASSWORD',
        'FND_NOTIFICATIONS_ACCESS_TOKEN',
        'FND_IDENTITY_SERVER_ACCESS_TOKEN',
        'FND_GATEWAY_ACCESS_TOKEN',
        // Iam envs
        'IAM_COLLECTOR_BASE_URL',
        'IAM_COLLECTOR_ADMIN_USERNAME',
        'IAM_COLLECTOR_ADMIN_PASSWORD',
        'IAM_USERS_ACCESS_TOKEN',
        'IAM_USERS_IS_BASE_URL',
        'IAM_USERS_IS_REALM',
        'IAM_USERS_IS_CLIENT_ID',
        'IAM_USERS_IS_CLIENT_SECRET',
        'IAM_USERS_IS_ADMIN_REALM',
        'IAM_USERS_IS_ADMIN_CLIENT_ID',
        'IAM_USERS_IS_ADMIN_CLIENT_SECRET',
        'IAM_USERS_IS_ADMIN_USERNAME',
        'IAM_USERS_IS_ADMIN_PASSWORD',
        'IAM_USERS_IS_SERVICE_ACCOUNT_USERNAME',
        'IAM_USERS_IS_SERVICE_ACCOUNT_PASSWORD',
        'IAM_USERS_META_ACCESS_TOKEN',
        'IAM_GROUPS_ACCESS_TOKEN',
        'IAM_POLICIES_ACCESS_TOKEN',
        // Pipelines envs
        'PIPELINES_COLLECTOR_BASE_URL',
        'PIPELINES_COLLECTOR_ADMIN_USERNAME',
        'PIPELINES_COLLECTOR_ADMIN_PASSWORD',
        'PIPELINES_CONFIGMAP_VAULT_BASE_URL',
        'PIPELINES_CONFIGMAP_VAULT_ACCESS_TOKEN',
        'PIPELINES_CONFIGMAP_VAULT_UNSEAL_KEY_1',
        'PIPELINES_CONFIGMAP_VAULT_UNSEAL_KEY_2',
        'PIPELINES_CONFIGMAP_VAULT_UNSEAL_KEY_3',
        'PIPELINES_CONFIGMAP_VAULT_UNSEAL_KEY_4',
        'PIPELINES_CONFIGMAP_VAULT_UNSEAL_KEY_5',
        'PIPELINES_TEMPLATE_CATALOG_ACCESS_TOKEN',
        'PIPELINES_ORCHESTRATOR_ACCESS_TOKEN',
        'PIPELINES_DEDICATED_GITHUB_ORGANIZATION',
        'PIPELINES_DEDICATED_FORM_GITHUB_ORGANIZATION',
        'PIPELINES_DEDICATED_FORM_GITHUB_REPOSITORY',
        'PIPELINES_DEDICATED_FORM_GITHUB_PROJECT_NAME',
        'PIPELINES_DEDICATED_FORM_GITHUB_PROJECT_NUMBER',
        'PIPELINES_DEDICATED_FORM_GITHUB_PROJECT_STATUS_ID',
        'PIPELINES_DEDICATED_FORM_GITHUB_PROJECT_STATUS_OPTION_TRIAGE',
        'PIPELINES_DEDICATED_FORM_GITHUB_PROJECT_STATUS_OPTION_APPROVED',
        'PIPELINES_DEDICATED_FORM_GITHUB_PROJECT_STATUS_OPTION_IN_PROGRESS',
        'PIPELINES_DEDICATED_FORM_GITHUB_PROJECT_STATUS_OPTION_IN_REVIEW',
        'PIPELINES_DEDICATED_FORM_GITHUB_PROJECT_STATUS_OPTION_DONE',
        // Lab envs
        'LAB_COLLECTOR_BASE_URL',
        'LAB_COLLECTOR_ADMIN_USERNAME',
        'LAB_COLLECTOR_ADMIN_PASSWORD',
        'LAB_CONFIGMAP_VAULT_ACCESS_TOKEN',
        'LAB_SHELL_CATALOG_ACCESS_TOKEN',
        'LAB_ORCHESTRATOR_ACCESS_TOKEN',
        // Monitoring
        'MONITORING_SUMMARY_DASHBOARD_URL',
        // Generic
        'LOG_LEVEL'
    ];

    private array $env = [];

    public function __construct()
    {
        foreach (self::ALLOWED_KEYS as $key) {
            $this->env[$key] = getenv($key) !== false ? getenv($key) : null;
        }
    }

    public function get(string $key, $default = null)
    {
        return $this->env[$key] ?? $default;
    }

    public function all(): array
    {
        return $this->env;
    }
}
