version: 0.1.0

nanorest:
  application:
    name: ${XPIPE_LIB_NANOREST_APPLICATION_NAME:notifications}
    version: ${XPIPE_LIB_NANOREST_APPLICATION_VERSION:v1}
    # Logger levels (severe, warning, info, debug, off)
    logger: ${XPIPE_LIB_NANOREST_APPLICATION_LOGGER:info}
  datasource:
    driverClassName: ${XPIPE_LIB_NANOREST_DB_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
    url: ${XPIPE_LIB_NANOREST_DB_CONNECTION_URL:jdbc:mysql://172.16.10.222:3306/app?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=5000}
    username: ${XPIPE_LIB_NANOREST_DB_USERNAME:root}
    password: ${XPIPE_LIB_NANOREST_DB_PASSWORD:secret}
    host: ${XPIPE_LIB_NANOREST_DB_HOST:172.16.10.222}
    port: ${XPIPE_LIB_NANOREST_DB_PORT:3306}
    schema: ${XPIPE_LIB_NANOREST_DB_SCHEMA:app}
  nanohttpd:
    port: ${XPIPE_LIB_NANOREST_NANOHTTPD_PORT:8080}
#  orm:
#    # ORM ddl auto (create, create-drop, validate, update)
#    ddlAuto: update
#    showSql: false

app:
  bitbucket:
    username: ${XPIPE_LIB_NANOREST_BITBUCKET_USERNAME:user}
    token: ${XPIPE_LIB_NANOREST_BITBUCKET_TOKEN:secret}
  github:
    username: ${XPIPE_LIB_NANOREST_GITHUB_USERNAME:user}
    token: ${XPIPE_LIB_NANOREST_GITHUB_TOKEN:secret}
  gitea:
    username: ${XPIPE_LIB_NANOREST_GITEA_USERNAME:user}
    token: ${XPIPE_LIB_NANOREST_GITEA_TOKEN:secret}
  jenkins:
    username: ${XPIPE_LIB_NANOREST_JENKINS_USERNAME:user}
    token: ${XPIPE_LIB_NANOREST_JENKINS_TOKEN:secret}
  cmdbuild:
    username: ${XPIPE_LIB_NANOREST_CMDBUILD_USERNAME:user}
    token: ${XPIPE_LIB_NANOREST_CMDBUILD_TOKEN:secret}