<?php
/**
 * Copyright © Sindria, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<div class="block block-contact-maps">
    <iframe id="contact-maps" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d89547.07313706506!2d9.107692348829907!3d45.462832850126134!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4786c1493f1275e7%3A0x3cffcd13c6740e8d!2sMilan%2C%20Metropolitan%20City%20of%20Milan%2C%20Italy!5e0!3m2!1sen!2sde!4v1648364199151!5m2!1sen!2sde" width="95%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

<style>
    @media screen and (max-width: 1240px) {
        .block-contact-maps {
            margin: auto;
            width: 95%;
            margin-bottom: 45px;
        }

        #contact-form {
            margin-bottom: 45px;
        }

        #contact-maps {
            height: 350px;
        }
    }
</style>
