<?php
/** @var $block Pipelines\Configmap\Block\Adminhtml\Configmap */

use Pipelines\Configmap\Helper\ConfigmapHelper;

$username = $block->getCurrentUser()->getUsername();
$configmaps = $block->getConfigmaps();
$attachedGroups = $block->getAttachedGroupsToUser();
$currentConfigmap = $block->getConfigmapId();
$currentOwner = $block->getCurrentOwner();


$action = $block->getUrl("configmap/index/choose", ['configmap_id' => $currentConfigmap, 'isAjax' => false]);

?>




<?php foreach ($block->getMessages() as $message): ?>
    <?php
    $type = $message->getType(); // es: 'error', 'success'
    $text = $message->getText();
    $cssClass = "message message-{$type} {$type}";
    ?>
    <div class="<?= $cssClass ?>">
        <div data-ui-id="messages-message-<?= $type ?>">
            <?= $block->escapeHtml($text) ?>
        </div>
    </div>
<?php endforeach; ?>

<form action="<?= $action ?>" method="post">

    <?= $block->getBlockHtml('formkey') ?>

    <div class="entry-edit form-inline">
        <div class="fieldset-wrapper">
            <div class="admin__fieldset-wrapper-content _hide">

                <fieldset class="admin__fieldset">

                    <div class="admin__field _required">
                        <div class="admin__field-label">

                            <label for="BQQFMJB">
                                <span>Owner</span>
                            </label>

                        </div>
                        <div class="admin__field-control">
                            <select onchange="this.form.submit()" class="admin__control-select" name="owner" id="BQQFMJB">
                                <option value="">-- Select Owner --</option>
                                <?php foreach ($attachedGroups as $group): ?>
                                    <option data-title="XPipe System" value="<?= $group['slug'] ?>" <?= $currentOwner === $group['slug'] ? " selected" : ""?> ><?= $group['label'] ?></option>
                                <?php endforeach; ?>

                            </select>

                        </div>
                    </div>


                    <div class="admin__field _required">
                        <div class="admin__field-label">

                            <label for="BQQFMJB">
                                <span>Configmap</span>
                            </label>

                        </div>
                        <div class="admin__field-control">
                            <select onchange="this.form.submit()" class="admin__control-select" name="configmap_id" id="BQQFMJB">
                                <option value="">Create new Configmap</option>
                                <?php foreach ($configmaps as $configmap): ?>
                                    <option data-title="XPipe System" value="<?= $configmap ?>" <?= $currentConfigmap === $configmap ? " selected" : ""?>  ><?= ConfigmapHelper::makeLabelFromSlug($configmap) ?></option>
                                <?php endforeach; ?>

                            </select>

                        </div>
                    </div>

                </fieldset>

            </div>
        </div>

    </div>
</form>

