<?php
/** @var $block Pipelines\Configmap\Block\Adminhtml\Configmap */

use Pipelines\Configmap\Helper\ConfigmapHelper;

$username = $block->getCurrentUser()->getUsername();

$configmaps = $block->getConfigmaps();

//dd(\Pipelines\Configmap\Helper\ConfigmapHelper::makeLabelFromSlug($configmaps[0]));

$action = $block->getUrl("configmap/index/choose", ['configmap_id' => $block->getConfigmapId(), 'isAjax' => false]);
//dd($action);


?>


<form action="<?= $action ?>" method="post">

    <?= $block->getBlockHtml('formkey') ?>
    <input name="owner" type="hidden" value="<?= $username ?>" />



    <div class="entry-edit form-inline">
        <div class="fieldset-wrapper">
            <div class="admin__fieldset-wrapper-content _hide">

                <fieldset class="admin__fieldset">

                    <div class="admin__field _required">
                        <div class="admin__field-label">

                            <label for="BQQFMJB">
                                <span>Configmap</span>
                            </label>

                        </div>
                        <div class="admin__field-control">

                            <select onchange="this.form.submit()" class="admin__control-select" name="configmap" id="BQQFMJB">
                                <option value="">-- Please Select --</option>
                                <?php foreach ($configmaps as $configmap): ?>
                                    <option data-title="XPipe System" value="<?= $configmap ?>"><?= ConfigmapHelper::makeLabelFromSlug($configmap) ?></option>
                                <?php endforeach; ?>

                            </select>

                        </div>
                    </div>

                </fieldset>

            </div>
        </div>

    </div>
</form>

