apiVersion: v1
kind: ConfigMap
metadata:
  name: xpipe-v1-api-collector-idx-config
  namespace: xpipe-cloud
data:
  ES_JAVA_OPTS: "-Xmx1024m -Xms1024m"
  cluster.name: "xpipe-v1-api-collector"
  #xpack.security.enabled: true
  # Use single node discovery in order to disable production mode and avoid bootstrap checks.
  # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
  discovery.type: "single-node"
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: xpipe-v1-api-collector-idx-secret
  namespace: xpipe-cloud
stringData:
  ELASTIC_PASSWORD: "secret"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: xpipe-v1-api-collector-idx
  name: xpipe-v1-api-collector-idx-pvc
  namespace: xpipe-cloud
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xpipe-v1-api-collector-idx
  name: xpipe-v1-api-collector-idx
  namespace: xpipe-cloud
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xpipe-v1-api-collector-idx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xpipe-v1-api-collector-idx
    spec:
      initContainers:
        - name: init-lostfound
          image: busybox
          command: [ "sh", "-c", "rm -Rf /usr/share/elasticsearch/data/lost+found" ]
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: xpipe-v1-api-collector-idx-volume
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
        #- name: init-elasticdata
        #  image: elasticsearch:7.13.3
        #  command: [ "bash", "-c", "yum install -y rsync && rsync -ravP /usr/share/elasticsearch/data/ /data/" ]
        #  volumeMounts:
        #    - mountPath: /data
        #      name: xpipe-v1-api-collector-idx-volume
        #  resources:
        #    requests:
        #      cpu: 10m
        #      memory: 10Mi
        - name: init-elasticsearch
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:0 /usr/share/elasticsearch/data" ]
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: xpipe-v1-api-collector-idx-volume
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
      containers:
      - env:
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              key: ES_JAVA_OPTS
              name: xpipe-v1-api-collector-idx-config
        - name: cluster.name
          valueFrom:
            configMapKeyRef:
              key: cluster.name
              name: xpipe-v1-api-collector-idx-config
        - name: discovery.type
          valueFrom:
            configMapKeyRef:
              key: discovery.type
              name: xpipe-v1-api-collector-idx-config
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ELASTIC_PASSWORD
              name: xpipe-v1-api-collector-idx-secret
        image: elasticsearch:7.13.3
        imagePullPolicy: IfNotPresent
        #command: [ "tail" ]
        #args: [ "-f", "/dev/null" ]
#        livenessProbe:
#          exec:
#            command:
#            - /bin/sh
#            - -i
#            - -c
#            -  mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
#          failureThreshold: 3
#          initialDelaySeconds: 30
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 1
        name: xpipe-v1-api-collector-idx
        ports:
        - containerPort: 9200
          protocol: TCP
        - containerPort: 9300
          protocol: TCP
#        readinessProbe:
#          exec:
#            command:
#            - /bin/sh
#            - -ec
#            - set -ex
#            - mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'
#          failureThreshold: 3
#          initialDelaySeconds: 5
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 1
        resources:
          limits:
            memory: 2048Mi
          requests:
            memory: 2048Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: xpipe-v1-api-collector-idx-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: xpipe-v1-api-collector-idx-volume
        persistentVolumeClaim:
          claimName: xpipe-v1-api-collector-idx-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xpipe-v1-api-collector-idx
  name: xpipe-v1-api-collector-idx
  namespace: xpipe-cloud
spec:
  ports:
  - name: elasticsearch
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: elasticsearch-internal
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: xpipe-v1-api-collector-idx
  sessionAffinity: None
  type: ClusterIP