---
name: ci

permissions: read-all

on:
  pull_request:

jobs:
  lint-docker-compose-file:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: lint zammad docker-compose file
        run: docker-compose config

  super-linter:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v6
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
