# global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: '@@MONITOR_LABEL@@'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - 'rules/*.yml'

# alert
alerting:
  alertmanagers:
  - scheme: @@ALERTMANAGER_SCHEME@@
    static_configs:
    - targets:
      - "@@ALERTMANAGER_HOST@@:@@ALERTMANAGER_PORT@@"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:9090']

scrape_config_files:
  #@@- 'configs/self.yml'
  #- 'configs/monitoring.yml'
  #- 'configs/apm.yml'
  - 'configs/@@SCRAPE_CONFIG@@.yml'