---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lab-v1-api-collector
  name: lab-v1-api-collector
  namespace: xpipe-cloud
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: lab-v1-api-collector
  sessionAffinity: None
  type: ClusterIP