scrape_configs:
  - job_name: 'cadvisor'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.cadvisor'
        type: 'A'
        port: 8080
    static_configs:
      - targets: [ 'wopr-lab-ph-lnx-cpn-1.sindria.corp:8080', 'wopr-lab-ph-lnx-wrk-1.sindria.corp:8080', 'wopr-lab-ph-lnx-wrk-2.sindria.corp:8080', 'wopr-lab-ph-lnx-wrk-3.sindria.corp:8080' ]