scrape_configs:
  - job_name: 'kubelet'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.kubelet'
        type: 'A'
        port: 10250
    scheme: https
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /etc/prometheus/k8s-sa-token.pem
    static_configs:
      - targets:
          - wopr-lab-ph-lnx-cpn-1.sindria.corp:10250
          - wopr-lab-ph-lnx-wrk-1.sindria.corp:10250
          - wopr-lab-ph-lnx-wrk-2.sindria.corp:10250
          - wopr-lab-ph-lnx-wrk-3.sindria.corp:10250