scrape_configs:
  - job_name: 'self'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.self'
        type: 'A'
        port: 9100
    static_configs:
      - targets: [ 'monitoring-self.local:9100' ]