<?php
/**
 * Copyright © Sindria, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block
 */
//dd($block);

?>



<!--<button id="clear-cart" class="action tocart primary" title="--><?//= __('Clear Cart') ?><!--" >--><?//= __('Clear Cart') ?><!--</button>-->

<script>

    //$.ajax({
    //    url: '<?php //echo $block->getUrl('core/items/remove');?>//',
    //    type: 'POST',
    //    showLoader: true,
    //    success: function (res) {
    //    if (res.messages) {
    //        $('[data-placeholder="messages"]').html(res.messages);
    //    }
    //
    //    if (res.minicart) {
    //        $('[data-block="minicart"]').replaceWith(res.minicart);
    //        $('[data-block="minicart"]').trigger('contentUpdated');
    //    }
    //}
    //});

</script>

<!--<script type="text/x-magento-init">-->
<!--    {-->
<!--        "*": {-->
<!--            "Core_Cart/js/test": {}-->
<!--        }-->
<!--    }-->
<!---->
<!--</script>-->

