{
 "title": "Ingress NGINX DaemonSet Overview",
 "description": "Overview of Ingress NGINX Controller deployed as a DaemonSet",
 "tags": [
  "kubernetes",
  "ingress",
  "nginx"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": "label_values(node_name, node)" },
   {
    "name": "host",
    "query": "label_values(nginx_ingress_controller_request_size_count, host)"
   },
   {
    "name": "path",
    "query": "label_values(nginx_ingress_controller_request_size_count{host=~\"$host\"}, path)"
   }
  ]
 },
 "panels": [
  {
   "title": "current connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{node=~\"$node\"}[1m]))"
    }
   ]
  },
  {
   "title": "avg requests/min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{node=~\"$node\", host=~\"$host\", path=~\"$path\"}[1m]))"
    }
   ]
  },
  {
   "title": "avg request time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{node=~\"$node\", host=~\"$host\", path=~\"$path\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "success rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{node=~\"$node\",status!~\"[4-5].*\"}[$__rate_interval])) / sum(rate(nginx_ingress_controller_requests{node=~\"$node\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "2xx reqs/min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{node=~\"$node\", status=~\"2.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "3xx reqs/min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{node=~\"$node\", status=~\"3.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "4xx reqs/min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{node=~\"$node\", status=~\"4.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "5xx reqs/min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_requests{node=~\"$node\", status=~\"5.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "nginx connections/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "conn/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_connections_total{node=~\"$node\"}[$__rate_interval])) by (state)",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "requests per minute (status)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{node=~\"$node\", host=~\"$host\", path=~\"$path\"}[1m])) by (status) > 0 ",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "percentile response times & transfer rates",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(label_join(rate(nginx_ingress_controller_request_duration_seconds_bucket{node=~\"$node\", host=~\"$host\", path=~\"$path\"}[1m]), \"url\", \"\", \"host\", \"path\")) by (le, url)) > -1"
    },
    {
     "expr": "histogram_quantile(0.90, sum(label_join(rate(nginx_ingress_controller_request_duration_seconds_bucket{node=~\"$node\", host=~\"$host\", path=~\"$path\"}[1m]), \"url\", \"\", \"host\", \"path\")) by (le, url)) > -1"
    },
    {
     "expr": "histogram_quantile(0.99, sum(label_join(rate(nginx_ingress_controller_request_duration_seconds_bucket{node=~\"$node\", host=~\"$host\", path=~\"$path\"}[1m]), \"url\", \"\", \"host\", \"path\")) by (le, url)) > -1"
    },
    {
     "expr": "sum(label_join(irate(nginx_ingress_controller_request_size_sum{node=~\"$node\", host=~\"$host\", path=~\"$path\"}[$__rate_interval]), \"url\", \"\", \"host\", \"path\")) by (url)"
    },
    {
     "expr": "sum(label_join(irate(nginx_ingress_controller_response_size_sum{node=~\"$node\", host=~\"$host\", path=~\"$path\"}[$__rate_interval]), \"url\", \"\", \"host\", \"path\")) by (url)"
    }
   ]
  },
  {
   "title": "requests duration (2.5min buckets)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum by (le)(\r\n  increase(\r\n    nginx_ingress_controller_request_duration_seconds_bucket{\r\n      node =~ \"$node\",\r\n      host =~ \"$host\",\r\n      path =~ \"$path\"\r\n    }[150s]\n  )\r\n)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "requests per minute (ingress)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "rpm" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{node=~\"$node\", host=~\"$host\", path=~\"$path\"}[1m])) by(node, host, path)",
     "legendFormat": "{{host}}{{path}} ({{node}})"
    }
   ]
  },
  {
   "title": "network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum (irate (nginx_ingress_controller_response_size_sum{node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "avg memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{node=~\"$node\"})",
     "legendFormat": "memory |"
    }
   ]
  },
  {
   "title": "avg cpu usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_nginx_process_cpu_seconds_total{node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "cpu |"
    }
   ]
  }
 ]
}