<!--<!--<script src="https://cdn.tiny.cloud/1/jrdqrdzy5tpwliuenm9l1u6ab3jttzbx5yy2ljdszm4ik8qr/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>-->-->
<!--<script>-->
<!--    // tinymce.init({-->
<!--    //     selector: 'textarea',-->
<!--    //     plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount',-->
<!--    //     toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table | align lineheight | numlist bullist indent outdent | emoticons charmap | removeformat',-->
<!--    // });-->
<!--</script>-->