<?php
/** @var Pipe\Dashboard\Block\Adminhtml\Dashboard $block */

// Grafana
//$dashboardDemo = "http://localhost:5007/public-dashboards/178a94bbe8b24449bce77a8d04d39edb";

// Metabase
$dashboardDemo = "http://localhost:5006/public/dashboard/f7925f52-9537-4141-9004-d39b87787649";

$block->consumeErrorMessages();
?>

<?php foreach ($block->getMessages() as $message): ?>
    <?php
    $type = $message->getType(); // es: 'error', 'success'
    $text = $message->getText();
    $cssClass = "message message-{$type} {$type}";
    ?>
    <div class="<?= $cssClass ?>">
        <div data-ui-id="messages-message-<?= $type ?>">
            <?= $block->escapeHtml($text) ?>
        </div>
    </div>
<?php endforeach; ?>

<!-- 1:1 aspect ratio -->
<div class="embed-responsive embed-responsive-21by9">
    <iframe class="embed-responsive-item" frameborder="0" src="<?= $dashboardDemo ?>"></iframe>
</div>



<style>
    /* Embed - bootstrap classes */

    .embed-responsive {
        position: relative;
        display: block;
        width: 100%;
        padding: 0;
        overflow: hidden;
    }
    .embed-responsive::before {
        display: block;
        content: "";
    }
    .embed-responsive .embed-responsive-item,
    .embed-responsive iframe,
    .embed-responsive embed,
    .embed-responsive object,
    .embed-responsive video {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        border: 0;
    }

    .embed-responsive-21by9::before {
        padding-top: 42.85714286%;
    }


    .form-container {
        display: none !important;
    }

    label {
        display: inline-block;
        margin-bottom: 0.0rem;
    }
</style>
