apiVersion: batch/v1
kind: Job
metadata:
  name: magento-post-deploy
  namespace: xpipe-dorjecurreli
spec:
  ttlSecondsAfterFinished: 120
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: magento-cli
        image: sindriainc/lab-v1-api-collector:@@RELEASE_VERSION@@
        command:
          - sh
          - -c
          - |
            php bin/magento setup:upgrade && php bin/magento setup:static-content:deploy it_IT en_US -f && php bin/magento setup:di:compile && php bin/magento cache:flush && echo "Magento post-deploy complete"
        envFrom:
        - configMapRef:
            name: lab-v1-api-collector-config
        - secretRef:
            name: lab-v1-api-collector-secret
        volumeMounts:
        - mountPath: /var/www/app/pub/static
          name: lab-v1-api-collector-static-volume
        - mountPath: /var/www/app/pub/media
          name: lab-v1-api-collector-media-volume
        - mountPath: /var/www/app/generated
          name: lab-v1-api-collector-generated-volume
        - mountPath: /var/www/app/var
          name: lab-v1-api-collector-var-volume
      volumes:
      - name: lab-v1-api-collector-static-volume
        persistentVolumeClaim:
          claimName: lab-v1-api-collector-static-pvc
      - name: lab-v1-api-collector-media-volume
        persistentVolumeClaim:
          claimName: lab-v1-api-collector-media-pvc
      - name: lab-v1-api-collector-generated-volume
        persistentVolumeClaim:
          claimName: lab-v1-api-collector-generated-pvc
      - name: lab-v1-api-collector-var-volume
        persistentVolumeClaim:
          claimName: lab-v1-api-collector-var-pvc
