---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: besteam-v1-web-website
  name: besteam-v1-web-website-code-pvc
  namespace: besteam-iaas
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 16Gi
---