route:
  receiver: 'telegram'
  #receiver: 'slack'
#  - match:
#      severity: test-telegram
#      receiver: stardata-telegram

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: YOUR_BOT_TOKEN
        api_url: https://api.telegram.org
        chat_id: YOUR_CHAT_ID
        parse_mode: ''
#  - name: 'slack'
#    slack_configs:
#       - send_resolved: true
#         username: '<username>'
#         channel: '#<channel-name>'
#         api_url: '<incomming-webhook-url>'