---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: iam-v1-api-collector
  name: iam-v1-api-collector-static-pvc
  namespace: xpipe-dorjecurreli
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn-wrk-3-storageclass
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: iam-v1-api-collector
  name: iam-v1-api-collector-media-pvc
  namespace: xpipe-dorjecurreli
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn-wrk-3-storageclass
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: iam-v1-api-collector
  name: iam-v1-api-collector-generated-pvc
  namespace: xpipe-dorjecurreli
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn-wrk-3-storageclass
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: iam-v1-api-collector
  name: iam-v1-api-collector-var-pvc
  namespace: xpipe-dorjecurreli
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn-wrk-3-storageclass
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: iam-v1-api-collector
  name: iam-v1-api-collector-vendor-pvc
  namespace: xpipe-dorjecurreli
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: longhorn-wrk-3-storageclass
  resources:
    requests:
      storage: 2Gi
---