apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wopr-vm-storageclass
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - noatime
  - nodiratime
  - commit=60
