version: '3.7'

services:
  # =app
  app:
    image: "sindriaproject/sindria-ingress:local"
    container_name: "${APP_NAME}"
    #command: tail -f /dev/null
    restart: always
    working_dir: /etc/nginx
    hostname: "${APP_NAME}.local"
    ports:
      - 80:80
      - 443:443
    #network_mode: "host"
    #cap_add:
    #  - NET_ADMIN
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #  vpc_sindria-ingress:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"

# =networks
networks:
  default:
    name: "vpc_xpipe"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_sindria-ingress:
#    external: true