http.host: 0.0.0.0
log.format: json
xpack.monitoring.elasticsearch.hosts:
- @@ELASTICSEARCH_PROTOCOL@@://@@ELASTICSEARCH_HOST@@:@@ELASTICSEARCH_PORT@@
- @@ELASTICSEARCH_CONTROL_CENTER_PROTOCOL@@://@@ELASTICSEARCH_CONTROL_CENTER_HOST@@:@@ELASTICSEARCH_CONTROL_CENTER_PORT@@