apiVersion: v1
kind: ConfigMap
metadata:
  name: xpipe-desk-config
  namespace: xpipe-sindria
data:
  POSTGRESQL_OPTIONS: "pool=50"
  POSTGRESQL_DB_CREATE: "true"
  # Backup settings
  BACKUP_DIR: "/var/tmp/zammad"
  BACKUP_TIME: "03:00"
  HOLD_DAYS: "10"
  TZ: "Europe/Berlin"
  AUTOWIZARD_RELATIVE_PATH: "'tmp/auto_wizard.json'"
  ELASTICSEARCH_ENABLED: "true"
  ELASTICSEARCH_SCHEMA: "http"
  ELASTICSEARCH_REINDEX: "true"
  ELASTICSEARCH_SSL_VERIFY: "false"
  NGINX_PORT: "8080"
  NGINX_SERVER_NAME: "_"
  NGINX_SERVER_SCHEME: "$scheme"
  RAILS_TRUSTED_PROXIES: "['127.0.0.1', '::1', '0.0.0.0']"
  ZAMMAD_WEB_CONCURRENCY: ""
  ZAMMAD_SESSION_JOBS: ""
  ZAMMAD_PROCESS_SCHEDULED: ""
  ZAMMAD_PROCESS_DELAYED_JOBS_WORKERS: ""