---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xpipe-desk
  name: xpipe-desk
  namespace: xpipe-sindria
spec:
  ports:
  - name: web
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: nginx
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: xpipe-desk
  sessionAffinity: None
  type: ClusterIP