<?php
/**
 * @var $block
 */
$pollUrl = $block->getUrl('notificationspoller/ajax/poll');
$audioUrl = $block->getViewFileUrl('Core_NotificationsPoller::sounds/task-completed-message-ringtone.mp3');
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Core_NotificationsPoller/js/notification-poller": {
                "url": "<?= $pollUrl ?>",
                "audio": "<?= $audioUrl ?>"
        }
    }
}
</script>


<script type="text/javascript">

    require(['notificationPoller'], function (initPoller) {
        console.log('[XPipe] Notification Poller initialized');
        //initPoller();
    });
</script>
