<div class="language-selector" style="display: inline-block; margin-left: 15px;">
    <select onchange="window.location.href=this.value;" style="padding: 5px 8px; border-radius: 6px; border: 1px solid #ccc;">
        <option value="https://xpipe.sindria.org/en" <?php echo ($block->getCurrentStoreCode() == 'default') ? 'selected' : ''; ?>>English</option>
        <option value="https://xpipe.sindria.org/it" <?php echo ($block->getCurrentStoreCode() == 'italian') ? 'selected' : ''; ?>>Italiano</option>
    </select>
</div>
