---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: xpipe-vault-cj
  namespace: xpipe-sindria
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: xpipe-vault-cj
        spec:
          containers:
          - env:
            - name: JAVA_OPTS
              value: -Xmx512m -Djavax.net.ssl.trustStore=/deployments/certs/truststore.jks
            image: sindriainc/xpipe-no-backup-mysql:1.0.0
            imagePullPolicy: IfNotPresent
            #command: [ "/bin/bash" ]
            #args: [ "rm", "-rf", "/app/videos/*" ]
            name: xpipe-vault-cj
            resources:
              limits:
                memory: 1024Mi
              requests:
                memory: 1024Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            #volumeMounts:
            #  - mountPath: /data
            #    name: xpipe-vault-data-volume
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          #volumes:
          #  - name: xpipe-vault-data-volume
          #    persistentVolumeClaim:
          #      claimName: xpipe-vault-data-pvc
          #      #defaultMode: 420
  schedule: '0 5 * * *'
  startingDeadlineSeconds: 200
  successfulJobsHistoryLimit: 3
  suspend: false