apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: xpipe-vault-job
    job-name: xpipe-vault-job
  name: xpipe-vault-job
  namespace: xpipe-sindria
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: xpipe-vault-job
        job-name: xpipe-vault-job
    spec:
      containers:
      - env:
        - name: RESTORE_TAG
          valueFrom:
            configMapKeyRef:
              key: RESTORE_TAG
              name: xpipe-vault-backup-config
        - name: RESTORE_SCHEMA
          valueFrom:
            configMapKeyRef:
              key: RESTORE_SCHEMA
              name: xpipe-vault-backup-config
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              key: APP_NAME
              name: xpipe-vault-backup-config
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              key: AWS_DEFAULT_REGION
              name: xpipe-vault-backup-config
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: xpipe-vault-backup-secret
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: xpipe-vault-backup-secret
        - name: BACKUP_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              key: BACKUP_BUCKET_NAME
              name: xpipe-vault-backup-secret
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: xpipe-vault-backup-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: xpipe-vault-backup-secret
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: DB_NAME
              name: xpipe-vault-backup-secret
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: DB_HOST
              name: xpipe-vault-backup-secret
        image: sindriainc/xpipe-no-restore-mysql:1.0.0-8
        imagePullPolicy: Always
        name: xpipe-vault-job
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        #volumeMounts:
        #- mountPath: /deployments/certs/truststore.jks
        #  name: xpipe-java-keystore-volume
        #  subPath: truststore.jks
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      #volumes:
      #- name: xpipe-java-keystore-volume
      #  secret:
      #    defaultMode: 420
      #    secretName: xpipe-java-keystore
