scrape_configs:
- job_name: kube
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 1m
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - wopr-lab-ph-lnx-wrk-3.sindria.corp:8080
    #- kube-state-metrics.kube-system.svc.cluster.local:8080