scrape_configs:
  - job_name: 'monitoring'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.monitoring'
        type: 'A'
        port: 9100
    static_configs:
      - targets: [ 'vpn.sindria.corp:9100', 'wopr-lab-ph-lnx-btn-1.sindria.corp:9100', 'wopr-lab-ph-lnx-cpn-1.sindria.corp:9100', 'wopr-lab-ph-lnx-wrk-1.sindria.corp:9100', 'wopr-lab-ph-lnx-wrk-2.sindria.corp:9100', 'wopr-lab-ph-lnx-wrk-3.sindria.corp:9100' ]