#!/usr/bin/env bash

source .env

# shellcheck disable=SC2046
docker run --rm -t --env IAC_MODE=${IAC_MODE} --env AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --env AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} --env AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} --env IAC_GIT_USERNAME=${IAC_GIT_USERNAME} --env IAC_GIT_PASSWORD=${IAC_GIT_PASSWORD} --env IAC_GIT_PROVIDER=${IAC_GIT_PROVIDER} --env IAC_GIT_NAMESPACE=${IAC_GIT_NAMESPACE} --env IAC_INFRA_NAME=${IAC_INFRA_NAME} --env IAC_CURRENT_INFRA=${IAC_CURRENT_INFRA} --env IAC_INVENTORY_REMOTE=${IAC_INVENTORY_REMOTE} --env IAC_INVENTORY_CACHE=${IAC_INVENTORY_CACHE} --env IAC_PRIVATE_KEY=${IAC_PRIVATE_KEY} --env IAC_INVENTORY_NAME=${IAC_INVENTORY_NAME} --env IAC_REMOTE_USER=${IAC_REMOTE_USER} --env HOST=${HOST} sindriainc/cm-docker-node:1.0.0