apiVersion: v1
kind: ConfigMap
metadata:
  name: xpipe-kvm-config
  namespace: xpipe-sindria
data:
  #BOOT: "https://dl-cdn.alpinelinux.org/alpine/v3.19/releases/x86_64/alpine-virt-3.19.1-x86_64.iso"
  BOOT: "https://download.freebsd.org/releases/amd64/amd64/ISO-IMAGES/14.0/FreeBSD-14.0-RELEASE-amd64-dvd1.iso"
  RAM_SIZE: "8G"
  CPU_CORES: "2"
  DISK_SIZE: "32G"
  VERSION: "win10"
  BOOT_MODE: "windows_plain"
  #VERSION: "https://example.com/win.iso"
  MANUAL: "Y"
  DHCP: "Y"
  DEVICE: "/dev/sda"
  DEVICE2: "/dev/sdb"
  ARGUMENTS: "-device usb-host,vendorid=0x1234,productid=0x1234"