---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xpipe-kvm
  name: xpipe-kvm
  namespace: xpipe-sindria
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xpipe-kvm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xpipe-kvm
    spec:
      imagePullSecrets:
      - name: sindria-dockerhub
      containers:
      - env:
        - name: BOOT
          valueFrom:
            configMapKeyRef:
              key: BOOT
              name: xpipe-kvm-config
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              key: VERSION
              name: xpipe-kvm-config
        - name: RAM_SIZE
          valueFrom:
            configMapKeyRef:
              key: RAM_SIZE
              name: xpipe-kvm-config
        - name: CPU_CORES
          valueFrom:
            configMapKeyRef:
              key: CPU_CORES
              name: xpipe-kvm-config
        - name: DISK_SIZE
          valueFrom:
            configMapKeyRef:
              key: DISK_SIZE
              name: xpipe-kvm-config
        #- name: MANUAL
        #  valueFrom:
        #    configMapKeyRef:
        #      key: MANUAL
        #      name: xpipe-kvm-config
        #- name: BOOT_MODE
        #  valueFrom:
        #    configMapKeyRef:
        #      key: BOOT_MODE
        #      name: xpipe-kvm-config
        #image: dockurr/windows:latest
        image: qemux/qemu-docker:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        #livenessProbe:
        #  failureThreshold: 3
        #  httpGet:
        #    path: /afc/channelactivity/actuator/health
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 50
        #  periodSeconds: 10
        #  successThreshold: 1
        #  timeoutSeconds: 1
        name: xpipe-kvm
        ports:
        - containerPort: 8006
          protocol: TCP
        - containerPort: 22
          protocol: TCP
        - containerPort: 3389
          protocol: TCP
        - containerPort: 3389
          protocol: UDP
        #readinessProbe:
        #  failureThreshold: 3
        #  httpGet:
        #    path: /afc/channelactivity/actuator/health
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 20
        #  periodSeconds: 10
        #  successThreshold: 1
        #  timeoutSeconds: 1
        resources:
          limits:
            memory: 8192Mi
          requests:
            memory: 8192Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/kvm
          name: xpipe-kvm-kvm-volume
        - mountPath: /dev/net/tun
          name: xpipe-kvm-tun-volume
        - mountPath: /storage
          name: xpipe-kvm-storage-volume
        #- mountPath: /dev/bus/usb
        #  name: xpipe-kvm-usb-volume
      dnsPolicy: ClusterFirst
      #hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: xpipe-kvm-storage-volume
        persistentVolumeClaim:
          claimName: xpipe-kvm-storage-pvc
          #defaultMode: 420
      - name: xpipe-kvm-kvm-volume
        hostPath:
          path: /dev/kvm
      - name: xpipe-kvm-tun-volume
        hostPath:
          path: /dev/net/tun
          type: CharDevice
      #- name: xpipe-kvm-usb-volume
      #  hostPath:
      #    path: /dev/bus/usb
---
