---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: xpipe-kvm
  name: xpipe-kvm-storage-pvc
  namespace: xpipe-sindria
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 64Gi