apiVersion: v1
kind: ConfigMap
metadata:
  name: core-v1-fnd-identityserver-config
  namespace: xpipe-cloud
data:
  KEYCLOAK_PROXY_ADDRESS_FORWARDING: "true"
  KEYCLOAK_DB_VENDOR: "mysql"
  KEYCLOAK_IMPORT: "/tmp/realm-export.json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-v1-fnd-identityserver-backup-config
  namespace: xpipe-cloud
data:
  AWS_DEFAULT_REGION: "eu-central-1"
  APP_NAME: "core-v1-fnd-identityserver"
  RESTORE_TAG: "latest"
  RESTORE_SCHEMA: ""