---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: xpipe-auth-cj
  namespace: xpipe-dev
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: xpipe-auth-cj
        spec:
          containers:
          - env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  key: APP_NAME
                  name: xpipe-auth-backup-config
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  key: AWS_DEFAULT_REGION
                  name: xpipe-auth-backup-config
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: xpipe-auth-backup-secret
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: xpipe-auth-backup-secret
            - name: BACKUP_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  key: BACKUP_BUCKET_NAME
                  name: xpipe-auth-backup-secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: xpipe-auth-backup-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: xpipe-auth-backup-secret
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: DB_NAME
                  name: xpipe-auth-backup-secret
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_HOST
                  name: xpipe-auth-backup-secret
            image: sindriainc/xpipe-no-backup-mysql:1.0.0-8
            imagePullPolicy: Always
            #command: [ "tail" ]
            #args: [ "-f", "/dev/null" ]
            name: xpipe-auth-cj
            resources:
              limits:
                memory: 1024Mi
              requests:
                memory: 1024Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            #volumeMounts:
            #  - mountPath: /data
            #    name: xpipe-auth-data-volume
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          #volumes:
          #  - name: xpipe-auth-data-volume
          #    persistentVolumeClaim:
          #      claimName: xpipe-auth-data-pvc
          #      #defaultMode: 420
  #schedule: '* * * * *'
  schedule: '0 5 * * *'
  startingDeadlineSeconds: 200
  successfulJobsHistoryLimit: 3
  suspend: false
