---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: core-v1-fnd-identityserver
  name: core-v1-fnd-identityserver
  namespace: xpipe-cloud
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: core-v1-fnd-identityserver
  sessionAffinity: None
  type: ClusterIP