version: '3.9'

services:
  # =app
  app:
    image: "jboss/keycloak:${KEYCLOAK_TAG}"
    container_name: "${APP_NAME}"
    #command: tail -f /dev/null
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=${KEYCLOAK_PROXY_ADDRESS_FORWARDING}
      - DB_VENDOR=${KEYCLOAK_DB_VENDOR}
      - DB_DATABASE=${KEYCLOAK_DB_DATABASE}
      - DB_ADDR=${KEYCLOAK_DB_ADDR}
      - DB_PORT=${KEYCLOAK_DB_PORT}
      - DB_USERNAME=${KEYCLOAK_DB_USERNAME}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      #- KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
       - "./${APP_DEPLOYMENTS_PATH}:/opt/jboss/keycloak/standalone/deployments"
      #- ./${APP_CONFIG_PATH}/local/realm-export.json:/tmp/realm-export.json
      #- "${BASE_PATH}/${PROJECT_PATH}/${APP_CONFIG_PATH}/local/realm-export.json:/tmp/realm-export.json"
      #- "${BASE_PATH}/${PROJECT_PATH}/${APP_DEPLOYMENTS_PATH}:/opt/jboss/keycloak/standalone/deployments"
    hostname: "${APP_DOMAIN}"
    ports:
      - "8083:8080"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_DOMAIN}"
    #networks:
    #  vpc_<app-name>:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_DOMAIN}"

# =networks
networks:
  default:
    name: "vpc_xpipe"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_devops:
#    external: true

# =volumes
#volumes:
#  db: