version: '3.9'

services:
  # =app
  app:
    image: "sindriainc/nginx-php:${NGINX_PHP_TAG}-${NGINX_PHP_VERSION}"
    container_name: "${APP_NAME}"
    command: /bin/bash -c "sudo chmod +x /usr/local/bin/startup.sh; /usr/local/bin/startup.sh& chmod +x /var/www/app/bin/run-scheduler.sh; /var/www/app/bin/run-scheduler.sh"
    #healthcheck:
    #  disable: true
    #entrypoint: /var/www/app/bin/run-scheduler.sh
    volumes:
      - "${BASE_PATH}/${PROJECT_PATH}/${CODE_PATH}:${APP_CODE_PATH}"
    hostname: "${APP_NAME}.local"
    ports:
      - "8083:80"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #  vpc_xdev:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"


# =networks
networks:
  default:
    name: "vpc_xpipe"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_xdev:
#    external: true