---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mc-nerdschool
  name: mc-nerdschool-world-pvc
  namespace: sindria-mc
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mc-nerdschool
  name: mc-nerdschool-logs-pvc
  namespace: sindria-mc
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mc-nerdschool
  name: mc-nerdschool-cache-pvc
  namespace: sindria-mc
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
