#version: '3.9'

services:
  # =app
  app:
    image: grafana/grafana:latest
    container_name: "${APP_NAME}"
    user: '472'
    #restart: always
    environment:
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
      - GF_SERVER_HTTP_PORT=${GF_SERVER_HTTP_PORT}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
      - GF_PANELS_DISABLE_SANITIZE_HTML=${GF_PANELS_DISABLE_SANITIZE_HTML}
      - GF_USERS_DEFAULT_THEME=${GF_USERS_DEFAULT_THEME}
    volumes:
      - data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    hostname: "${APP_DOMAIN}"
    ports:
      - "5007:5007"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_DOMAIN}"
    #networks:
    #  vpc_<app-name>:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_DOMAIN}"
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 4096M
#        reservations:
#          cpus: '0.50'
#          memory: 2048M
#    depends_on:
#      - engine

# =networks
networks:
  default:
    name: "vpc_xpipe"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_app_name:
#    external: true

# =volumes
volumes:
  data: {}
