<?php
/**
 * Copyright © Sindria, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block
 */
//dd($block);


?>


<div class="xpipe-changeme">
    <section class="xpipe-chat-avenue-messenger">
        <div class="xpipe-chat-menu">
            <div class="xpipe-chat-menu-items">
                <span>
                    <a class="xpipe-chat-minimize" href="#" title="Minimize">&mdash;</a>
                    <br />
                    <a class="xpipe-chat-close" href="#" title="End Chat">&#10005;</a>
                </span>
            </div>
            <div class="xpipe-chat-button">...</div>
        </div>
        <div class="xpipe-chat-agent-face">
            <div class="xpipe-chat-half">
                <img class="xpipe-chat-agent xpipe-chat-circle" src="https://agentpalmer.com/wp-content/uploads/2014/10/Irving-Metzman-as-Richter-standing-next-to-the-WOPR-War-Operations-Plan-Response.jpg" alt="Chat Avatar">
            </div>
        </div>
        <div class="xpipe-chat">
            <div class="xpipe-chat-title">
                <h1>Joshua</h1>
                <!--            <h2>RE/MAX</h2>-->
                <!--              <figure class="xpipe-chat-avatar">-->
                <!--                <img src="http://askavenue.com/img/17.jpg" />-->
                <!--              </figure>-->
            </div>
            <div class="xpipe-chat-messages">
                <div class="xpipe-chat-messages-content"></div>
            </div>
            <div class="xpipe-chat-message-box">
                <textarea type="text" class="xpipe-chat-message-input" placeholder="Type message..."></textarea>
                <button type="submit" class="xpipe-chat-message-submit">Send</button>
            </div>
        </div>

    </section>
    <!--<div class="xpipe-chat-bg"></div>-->
</div>



<script>

    (function  () {
        require(["jquery", "scroll"],function($) {

            var $messages = $('.xpipe-chat-messages-content'),
                d, h, m,
                i = 0;


            function updateScrollbar() {
                $messages.mCustomScrollbar("update").mCustomScrollbar('scrollTo', 'bottom', {
                    scrollInertia: 10,
                    timeout: 0
                });
            }


            function setDate(){
                d = new Date()
                if (m != d.getMinutes()) {
                    m = d.getMinutes();
                    $('<div class="xpipe-chat-message-timestamp">' + d.getHours() + ':' + m + '</div>').appendTo($('.xpipe-chat-message:last'));
                    $('<div class="xpipe-chat-message-checkmark-sent-delivered">&check;</div>').appendTo($('.xpipe-chat-message:last'));
                    $('<div class="xpipe-chat-message-checkmark-read">&check;</div>').appendTo($('.xpipe-chat-message:last'));
                }
            }


            function insertMessage() {
                msg = $('.xpipe-chat-message-input').val();
                console.log(msg);
                if ($.trim(msg) == '') {
                    return false;
                }
                $('<div class="xpipe-chat-message xpipe-chat-message-personal">' + msg + '</div>').appendTo($('.mCSB_container')).addClass('new');
                setDate();
                $('.xpipe-chat-message-input').val(null);
                updateScrollbar();
                setTimeout(function() {
                    fakeMessage();
                }, 1000 + (Math.random() * 20) * 100);
            }

            var Fake = [
                'Hi there, I\'m Joshua and you?',
                'Nice to meet you',
                'How are you?',
                'Not too bad, thanks',
                'What do you do?',
                'That\'s awesome',
                'XPipe is a nice place to stay',
                'I think you\'re a nice person',
                'Why do you think that?',
                'Can you explain?',
                'Anyway I\'ve gotta go now',
                'It was a pleasure chat with you',
                'Time to make a new pipeline',
                'Bye',
                ':)'
            ]


            function fakeMessage() {
                if ($('.xpipe-chat-message-input').val() != '') {
                    return false;
                }
                $('<div class="xpipe-chat-message xpipe-chat-message-loading xpipe-chat-message-new"><figure class="xpipe-chat-avatar"><img src="https://64.media.tumblr.com/c9dfec0eef9493e738265f6a15c129da/283fd3dd4f0601a9-cf/s1280x1920/8a7ff8a6dd7127734b798dc0beb88b05c04653e8.jpg" /></figure><span>...</span></div>').appendTo($('.mCSB_container'));
                updateScrollbar();

                setTimeout(function() {
                    console.log(Fake[i]);
                    $('.xpipe-chat-message.loading').remove();
                    $('<div class="xpipe-chat-message xpipe-chat-message-new"><figure class="xpipe-chat-avatar"><img src="https://64.media.tumblr.com/c9dfec0eef9493e738265f6a15c129da/283fd3dd4f0601a9-cf/s1280x1920/8a7ff8a6dd7127734b798dc0beb88b05c04653e8.jpg" /></figure>' + Fake[i] + '</div>').appendTo($('.mCSB_container')).addClass('new');
                    setDate();
                    updateScrollbar();
                    i++;
                }, 1000 + (Math.random() * 20) * 100);

            }


            $(window).load(function() {
                $messages.mCustomScrollbar();
                setTimeout(function() {
                    fakeMessage();
                }, 100);
            });

            $(document).ready(function() {

                $('.xpipe-chat-message-submit').click(function() {
                    insertMessage();
                });

                $(window).on('keydown', function(e) {
                    if (e.which == 13) {
                        insertMessage();
                        return false;
                    }
                })


                $('.xpipe-chat-button').click(function() {
                    $('.xpipe-chat-menu .xpipe-chat-menu-items span').toggleClass('active');
                    $('.xpipe-chat-menu .xpipe-chat-button').toggleClass('active');
                });

                // Minimize
                $('.xpipe-chat-minimize').click(function() {
                    //insertMessage();
                });



            });
        });
    })();

</script>
