package org.cmdbuild.services.soap.client.beans;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-05-16T09:39:11.468+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://soap.services.cmdbuild.org", name = "Private")
@XmlSeeAlso({ObjectFactory.class})
public interface Private {

    @WebMethod
    @RequestWrapper(localName = "getCardList", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardList")
    @ResponseWrapper(localName = "getCardListResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardListResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.CardList getCardList(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "attributeList", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Attribute> attributeList,
        @WebParam(name = "queryType", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Query queryType,
        @WebParam(name = "orderType", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Order> orderType,
        @WebParam(name = "limit", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long limit,
        @WebParam(name = "offset", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long offset,
        @WebParam(name = "fullTextQuery", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String fullTextQuery,
        @WebParam(name = "cqlQuery", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.CqlQuery cqlQuery
    );

    @WebMethod
    @RequestWrapper(localName = "getClassSchemaByName", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetClassSchemaByName")
    @ResponseWrapper(localName = "getClassSchemaByNameResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetClassSchemaByNameResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.ClassSchema getClassSchemaByName(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "includeAttributes", targetNamespace = "http://soap.services.cmdbuild.org")
        boolean includeAttributes
    );

    @WebMethod
    @RequestWrapper(localName = "getAttachmentList", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetAttachmentList")
    @ResponseWrapper(localName = "getAttachmentListResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetAttachmentListResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.Attachment> getAttachmentList(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "cardId", targetNamespace = "http://soap.services.cmdbuild.org")
        long cardId
    );

    @WebMethod
    @RequestWrapper(localName = "updateLookup", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UpdateLookup")
    @ResponseWrapper(localName = "updateLookupResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UpdateLookupResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public boolean updateLookup(
        @WebParam(name = "lookup", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Lookup lookup
    );

    @WebMethod
    @RequestWrapper(localName = "getRelationHistory", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetRelationHistory")
    @ResponseWrapper(localName = "getRelationHistoryResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetRelationHistoryResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.Relation> getRelationHistory(
        @WebParam(name = "relation", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Relation relation
    );

    @WebMethod
    @RequestWrapper(localName = "getActivityMenuSchema", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetActivityMenuSchema")
    @ResponseWrapper(localName = "getActivityMenuSchemaResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetActivityMenuSchemaResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.MenuSchema getActivityMenuSchema();

    @WebMethod
    @RequestWrapper(localName = "getLookupList", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetLookupList")
    @ResponseWrapper(localName = "getLookupListResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetLookupListResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.Lookup> getLookupList(
        @WebParam(name = "type", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String type,
        @WebParam(name = "value", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String value,
        @WebParam(name = "parentList", targetNamespace = "http://soap.services.cmdbuild.org")
        boolean parentList
    );

    @WebMethod
    @RequestWrapper(localName = "getMenuSchema", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetMenuSchema")
    @ResponseWrapper(localName = "getMenuSchemaResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetMenuSchemaResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.MenuSchema getMenuSchema();

    @WebMethod
    @RequestWrapper(localName = "resumeWorkflow", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.ResumeWorkflow")
    @ResponseWrapper(localName = "resumeWorkflowResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.ResumeWorkflowResponse")
    public void resumeWorkflow(
        @WebParam(name = "card", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Card card
    );

    @WebMethod
    @RequestWrapper(localName = "getClassSchema", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetClassSchema")
    @ResponseWrapper(localName = "getClassSchemaResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetClassSchemaResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.ClassSchema getClassSchema(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className
    );

    @WebMethod
    @RequestWrapper(localName = "callFunction", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CallFunction")
    @ResponseWrapper(localName = "callFunctionResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CallFunctionResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.Attribute> callFunction(
        @WebParam(name = "functionName", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String functionName,
        @WebParam(name = "params", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Attribute> params
    );

    @WebMethod
    @RequestWrapper(localName = "getActivityObjects", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetActivityObjects")
    @ResponseWrapper(localName = "getActivityObjectsResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetActivityObjectsResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.ActivitySchema getActivityObjects(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "cardid", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long cardid
    );

    @WebMethod
    @RequestWrapper(localName = "updateRelationAttributes", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UpdateRelationAttributes")
    @ResponseWrapper(localName = "updateRelationAttributesResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UpdateRelationAttributesResponse")
    public void updateRelationAttributes(
        @WebParam(name = "relation", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Relation relation,
        @WebParam(name = "attributes", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Attribute> attributes
    );

    @WebMethod
    @RequestWrapper(localName = "getRelationListExt", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetRelationListExt")
    @ResponseWrapper(localName = "getRelationListExtResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetRelationListExtResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.RelationExt> getRelationListExt(
        @WebParam(name = "domain", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String domain,
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "cardId", targetNamespace = "http://soap.services.cmdbuild.org")
        long cardId
    );

    @WebMethod
    @RequestWrapper(localName = "createCard", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CreateCard")
    @ResponseWrapper(localName = "createCardResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CreateCardResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public long createCard(
        @WebParam(name = "cardType", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Card cardType
    );

    @WebMethod
    @RequestWrapper(localName = "getReportList", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetReportList")
    @ResponseWrapper(localName = "getReportListResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetReportListResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.Report> getReportList(
        @WebParam(name = "type", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String type,
        @WebParam(name = "limit", targetNamespace = "http://soap.services.cmdbuild.org")
        long limit,
        @WebParam(name = "offset", targetNamespace = "http://soap.services.cmdbuild.org")
        long offset
    );

    @WebMethod
    @RequestWrapper(localName = "getCardHistory", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardHistory")
    @ResponseWrapper(localName = "getCardHistoryResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardHistoryResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.CardList getCardHistory(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "cardId", targetNamespace = "http://soap.services.cmdbuild.org")
        long cardId,
        @WebParam(name = "limit", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long limit,
        @WebParam(name = "offset", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long offset
    );

    @WebMethod
    @RequestWrapper(localName = "updateCard", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UpdateCard")
    @ResponseWrapper(localName = "updateCardResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UpdateCardResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public boolean updateCard(
        @WebParam(name = "card", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Card card
    );

    @WebMethod
    @RequestWrapper(localName = "getReportParameters", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetReportParameters")
    @ResponseWrapper(localName = "getReportParametersResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetReportParametersResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.AttributeSchema> getReportParameters(
        @WebParam(name = "id", targetNamespace = "http://soap.services.cmdbuild.org")
        long id,
        @WebParam(name = "extension", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String extension
    );

    @WebMethod
    @RequestWrapper(localName = "getCardListExt", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardListExt")
    @ResponseWrapper(localName = "getCardListExtResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardListExtResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.CardListExt getCardListExt(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "attributeList", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Attribute> attributeList,
        @WebParam(name = "queryType", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Query queryType,
        @WebParam(name = "orderType", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Order> orderType,
        @WebParam(name = "limit", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long limit,
        @WebParam(name = "offset", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long offset,
        @WebParam(name = "fullTextQuery", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String fullTextQuery,
        @WebParam(name = "cqlQuery", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.CqlQuery cqlQuery
    );

    @WebMethod
    @RequestWrapper(localName = "getReference", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetReference")
    @ResponseWrapper(localName = "getReferenceResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetReferenceResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.Reference> getReference(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "query", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Query query,
        @WebParam(name = "orderType", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Order> orderType,
        @WebParam(name = "limit", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long limit,
        @WebParam(name = "offset", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long offset,
        @WebParam(name = "fullTextQuery", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String fullTextQuery,
        @WebParam(name = "cqlQuery", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.CqlQuery cqlQuery
    );

    @WebMethod
    @RequestWrapper(localName = "getAttributeList", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetAttributeList")
    @ResponseWrapper(localName = "getAttributeListResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetAttributeListResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.AttributeSchema> getAttributeList(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className
    );

    @WebMethod
    @RequestWrapper(localName = "copyAttachment", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CopyAttachment")
    @ResponseWrapper(localName = "copyAttachmentResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CopyAttachmentResponse")
    public void copyAttachment(
        @WebParam(name = "sourceClassName", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String sourceClassName,
        @WebParam(name = "sourceId", targetNamespace = "http://soap.services.cmdbuild.org")
        long sourceId,
        @WebParam(name = "filename", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String filename,
        @WebParam(name = "destinationClassName", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String destinationClassName,
        @WebParam(name = "destinationId", targetNamespace = "http://soap.services.cmdbuild.org")
        long destinationId
    );

    @WebMethod
    @RequestWrapper(localName = "getFunctionList", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetFunctionList")
    @ResponseWrapper(localName = "getFunctionListResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetFunctionListResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.FunctionSchema> getFunctionList();

    @WebMethod
    @RequestWrapper(localName = "getLookupById", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetLookupById")
    @ResponseWrapper(localName = "getLookupByIdResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetLookupByIdResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.Lookup getLookupById(
        @WebParam(name = "id", targetNamespace = "http://soap.services.cmdbuild.org")
        long id
    );

    @WebMethod
    @RequestWrapper(localName = "getCardListWithLongDateFormat", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardListWithLongDateFormat")
    @ResponseWrapper(localName = "getCardListWithLongDateFormatResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardListWithLongDateFormatResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.CardList getCardListWithLongDateFormat(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "attributeList", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Attribute> attributeList,
        @WebParam(name = "queryType", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Query queryType,
        @WebParam(name = "orderType", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Order> orderType,
        @WebParam(name = "limit", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long limit,
        @WebParam(name = "offset", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long offset,
        @WebParam(name = "fullTextQuery", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String fullTextQuery,
        @WebParam(name = "cqlQuery", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.CqlQuery cqlQuery
    );

    @WebMethod
    @RequestWrapper(localName = "updateAttachmentDescription", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UpdateAttachmentDescription")
    @ResponseWrapper(localName = "updateAttachmentDescriptionResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UpdateAttachmentDescriptionResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public boolean updateAttachmentDescription(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "cardId", targetNamespace = "http://soap.services.cmdbuild.org")
        long cardId,
        @WebParam(name = "filename", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String filename,
        @WebParam(name = "description", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String description
    );

    @WebMethod
    @RequestWrapper(localName = "deleteRelation", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.DeleteRelation")
    @ResponseWrapper(localName = "deleteRelationResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.DeleteRelationResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public boolean deleteRelation(
        @WebParam(name = "relation", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Relation relation
    );

    @WebMethod
    @RequestWrapper(localName = "updateWorkflow", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UpdateWorkflow")
    @ResponseWrapper(localName = "updateWorkflowResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UpdateWorkflowResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.Workflow updateWorkflow(
        @WebParam(name = "card", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Card card,
        @WebParam(name = "completeTask", targetNamespace = "http://soap.services.cmdbuild.org")
        boolean completeTask,
        @WebParam(name = "widgets", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.WorkflowWidgetSubmission> widgets
    );

    @WebMethod
    @RequestWrapper(localName = "notify", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.Notify")
    @ResponseWrapper(localName = "notifyResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.NotifyResponse")
    public void notify(
        @WebParam(name = "event", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.AbstractEvent event
    );

    @WebMethod
    @RequestWrapper(localName = "createSession", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CreateSession")
    @ResponseWrapper(localName = "createSessionResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CreateSessionResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.lang.String createSession();

    @WebMethod
    @RequestWrapper(localName = "getCardMenuSchema", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardMenuSchema")
    @ResponseWrapper(localName = "getCardMenuSchemaResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardMenuSchemaResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.MenuSchema getCardMenuSchema();

    @WebMethod
    @RequestWrapper(localName = "getReport", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetReport")
    @ResponseWrapper(localName = "getReportResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetReportResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public javax.activation.DataHandler getReport(
        @WebParam(name = "id", targetNamespace = "http://soap.services.cmdbuild.org")
        long id,
        @WebParam(name = "extension", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String extension,
        @WebParam(name = "params", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.ReportParams> params
    );

    @WebMethod
    @RequestWrapper(localName = "createLookup", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CreateLookup")
    @ResponseWrapper(localName = "createLookupResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CreateLookupResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public long createLookup(
        @WebParam(name = "lookup", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Lookup lookup
    );

    @WebMethod
    @RequestWrapper(localName = "getLookupListByCode", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetLookupListByCode")
    @ResponseWrapper(localName = "getLookupListByCodeResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetLookupListByCodeResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.Lookup> getLookupListByCode(
        @WebParam(name = "type", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String type,
        @WebParam(name = "code", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String code,
        @WebParam(name = "parentList", targetNamespace = "http://soap.services.cmdbuild.org")
        boolean parentList
    );

    @WebMethod
    @RequestWrapper(localName = "getCardWithLongDateFormat", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardWithLongDateFormat")
    @ResponseWrapper(localName = "getCardWithLongDateFormatResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardWithLongDateFormatResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.CardExt getCardWithLongDateFormat(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "cardId", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long cardId,
        @WebParam(name = "attributeList", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Attribute> attributeList
    );

    @WebMethod
    @RequestWrapper(localName = "downloadAttachment", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.DownloadAttachment")
    @ResponseWrapper(localName = "downloadAttachmentResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.DownloadAttachmentResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public javax.activation.DataHandler downloadAttachment(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "objectid", targetNamespace = "http://soap.services.cmdbuild.org")
        long objectid,
        @WebParam(name = "filename", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String filename
    );

    @WebMethod
    @RequestWrapper(localName = "deleteAttachment", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.DeleteAttachment")
    @ResponseWrapper(localName = "deleteAttachmentResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.DeleteAttachmentResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public boolean deleteAttachment(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "cardId", targetNamespace = "http://soap.services.cmdbuild.org")
        long cardId,
        @WebParam(name = "filename", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String filename
    );

    @WebMethod
    @RequestWrapper(localName = "deleteCard", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.DeleteCard")
    @ResponseWrapper(localName = "deleteCardResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.DeleteCardResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public boolean deleteCard(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "cardId", targetNamespace = "http://soap.services.cmdbuild.org")
        long cardId
    );

    @WebMethod
    @RequestWrapper(localName = "getClassSchemaById", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetClassSchemaById")
    @ResponseWrapper(localName = "getClassSchemaByIdResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetClassSchemaByIdResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.ClassSchema getClassSchemaById(
        @WebParam(name = "classId", targetNamespace = "http://soap.services.cmdbuild.org")
        long classId,
        @WebParam(name = "includeAttributes", targetNamespace = "http://soap.services.cmdbuild.org")
        boolean includeAttributes
    );

    @WebMethod
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetUserInfo")
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetUserInfoResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.UserInfo getUserInfo();

    @WebMethod
    @RequestWrapper(localName = "uploadAttachment", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UploadAttachment")
    @ResponseWrapper(localName = "uploadAttachmentResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.UploadAttachmentResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public boolean uploadAttachment(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "objectid", targetNamespace = "http://soap.services.cmdbuild.org")
        long objectid,
        @WebParam(name = "file", targetNamespace = "http://soap.services.cmdbuild.org")
        javax.activation.DataHandler file,
        @WebParam(name = "filename", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String filename,
        @WebParam(name = "category", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String category,
        @WebParam(name = "description", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String description
    );

    @WebMethod
    @RequestWrapper(localName = "deleteLookup", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.DeleteLookup")
    @ResponseWrapper(localName = "deleteLookupResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.DeleteLookupResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public boolean deleteLookup(
        @WebParam(name = "lookupId", targetNamespace = "http://soap.services.cmdbuild.org")
        long lookupId
    );

    @WebMethod
    @RequestWrapper(localName = "getCard", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCard")
    @ResponseWrapper(localName = "getCardResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetCardResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public org.cmdbuild.services.soap.client.beans.Card getCard(
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "cardId", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long cardId,
        @WebParam(name = "attributeList", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Attribute> attributeList
    );

    @WebMethod
    @RequestWrapper(localName = "getProcessHelp", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetProcessHelp")
    @ResponseWrapper(localName = "getProcessHelpResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetProcessHelpResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.lang.String getProcessHelp(
        @WebParam(name = "classname", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String classname,
        @WebParam(name = "cardid", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.Long cardid
    );

    @WebMethod
    @RequestWrapper(localName = "getBuiltInReport", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetBuiltInReport")
    @ResponseWrapper(localName = "getBuiltInReportResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetBuiltInReportResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public javax.activation.DataHandler getBuiltInReport(
        @WebParam(name = "id", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String id,
        @WebParam(name = "extension", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String extension,
        @WebParam(name = "params", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.ReportParams> params
    );

    @WebMethod
    @RequestWrapper(localName = "getRelationList", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetRelationList")
    @ResponseWrapper(localName = "getRelationListResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetRelationListResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.Relation> getRelationList(
        @WebParam(name = "domain", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String domain,
        @WebParam(name = "className", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String className,
        @WebParam(name = "cardId", targetNamespace = "http://soap.services.cmdbuild.org")
        long cardId
    );

    @WebMethod
    @RequestWrapper(localName = "abortWorkflow", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.AbortWorkflow")
    @ResponseWrapper(localName = "abortWorkflowResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.AbortWorkflowResponse")
    public void abortWorkflow(
        @WebParam(name = "card", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Card card
    );

    @WebMethod
    @RequestWrapper(localName = "moveAttachment", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.MoveAttachment")
    @ResponseWrapper(localName = "moveAttachmentResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.MoveAttachmentResponse")
    public void moveAttachment(
        @WebParam(name = "sourceClassName", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String sourceClassName,
        @WebParam(name = "sourceId", targetNamespace = "http://soap.services.cmdbuild.org")
        long sourceId,
        @WebParam(name = "filename", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String filename,
        @WebParam(name = "destinationClassName", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String destinationClassName,
        @WebParam(name = "destinationId", targetNamespace = "http://soap.services.cmdbuild.org")
        long destinationId
    );

    @WebMethod
    @RequestWrapper(localName = "createRelation", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CreateRelation")
    @ResponseWrapper(localName = "createRelationResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CreateRelationResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public boolean createRelation(
        @WebParam(name = "relation", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Relation relation
    );

    @WebMethod
    @RequestWrapper(localName = "generateDigest", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GenerateDigest")
    @ResponseWrapper(localName = "generateDigestResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GenerateDigestResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.lang.String generateDigest(
        @WebParam(name = "plainText", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String plainText,
        @WebParam(name = "digestAlgorithm", targetNamespace = "http://soap.services.cmdbuild.org")
        java.lang.String digestAlgorithm
    ) throws NoSuchAlgorithmException_Exception;

    @WebMethod
    @RequestWrapper(localName = "suspendWorkflow", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.SuspendWorkflow")
    @ResponseWrapper(localName = "suspendWorkflowResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.SuspendWorkflowResponse")
    public void suspendWorkflow(
        @WebParam(name = "card", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Card card
    );

    @WebMethod
    @RequestWrapper(localName = "getRelationAttributes", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetRelationAttributes")
    @ResponseWrapper(localName = "getRelationAttributesResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.GetRelationAttributesResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public java.util.List<org.cmdbuild.services.soap.client.beans.Attribute> getRelationAttributes(
        @WebParam(name = "relation", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Relation relation
    );

    @WebMethod
    @RequestWrapper(localName = "createRelationWithAttributes", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CreateRelationWithAttributes")
    @ResponseWrapper(localName = "createRelationWithAttributesResponse", targetNamespace = "http://soap.services.cmdbuild.org", className = "org.cmdbuild.services.soap.client.beans.CreateRelationWithAttributesResponse")
    @WebResult(name = "return", targetNamespace = "http://soap.services.cmdbuild.org")
    public boolean createRelationWithAttributes(
        @WebParam(name = "relation", targetNamespace = "http://soap.services.cmdbuild.org")
        org.cmdbuild.services.soap.client.beans.Relation relation,
        @WebParam(name = "attributes", targetNamespace = "http://soap.services.cmdbuild.org")
        java.util.List<org.cmdbuild.services.soap.client.beans.Attribute> attributes
    );
}
