---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kali-console
  name: kali-console
  namespace: sindria-sec
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kali-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kali-console
    spec:
      imagePullSecrets:
      - name: sindria-dockerhub
      initContainers:
        - name: init-data
          image: busybox
          command: [ "sh", "-c", "chown -R 1000:1000 /var/www/app" ]
          volumeMounts:
            - mountPath: /var/www/app
              name: kali-console-data-volume
      containers:
      - env:
        - name: JAVA_OPTS
          value: "-Xmx4096M -Xms4096M"
        image: sindriainc/kali:3.0.0-rolling-amd64
        imagePullPolicy: IfNotPresent
        #securityContext:
        #  capabilities:
        #    add:
        #      - NET_ADMIN
        #livenessProbe:
        #  failureThreshold: 3
        #  httpGet:
        #    path: /afc/channelactivity/actuator/health
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 50
        #  periodSeconds: 10
        #  successThreshold: 1
        #  timeoutSeconds: 1
        name: kali-console
        tty: false
        stdin: true
        #command: [ "" ]
        command: [ "tail" ]
        args: [ "-f", "/dev/null" ]
        ports:
        - containerPort: 4444
          hostPort: 4444
          protocol: TCP
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        #readinessProbe:
        #  failureThreshold: 3
        #  httpGet:
        #    path: /afc/channelactivity/actuator/health
        #    port: 8080
        #    scheme: HTTP
        #  initialDelaySeconds: 20
        #  periodSeconds: 10
        #  successThreshold: 1
        #  timeoutSeconds: 1
        resources:
          limits:
            memory: 8192Mi
          requests:
            memory: 8192Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/app
          name: kali-console-data-volume
      dnsPolicy: ClusterFirst
      #hostNetwork: true
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kali-console-data-volume
        persistentVolumeClaim:
          claimName: kali-console-data-pvc
          #defaultMode: 420
---
