---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: kali-console
  name: kali-console-data-pvc
  namespace: sindria-sec
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 16Gi