---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kali-console
  name: kali-console
  namespace: sindria-sec
spec:
  ports:
  - name: reverse
    port: 4444
    protocol: TCP
    targetPort: 4444
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: alt-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: alt-https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: kali-console
  sessionAffinity: None
  type: ClusterIP