apiVersion: v1
kind: ConfigMap
metadata:
  name: xpipe-tracker-db-config
  namespace: xpipe-sindria
data:
  MYSQL_MAX_CONNECTIONS: "500"
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: xpipe-tracker-db-secret
  namespace: xpipe-sindria
stringData:
  MYSQL_ROOT_PASSWORD: "secret"
  MYSQL_DATABASE: "app"
  MYSQL_USER: "user"
  MYSQL_PASSWORD: "secret"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: xpipe-tracker-db
  name: xpipe-tracker-db-pvc
  namespace: xpipe-sindria
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xpipe-tracker-db
  name: xpipe-tracker-db
  namespace: xpipe-sindria
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xpipe-tracker-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xpipe-tracker-db
    spec:
      initContainers:
        - name: init-lostfound
          image: busybox
          command: [ "sh", "-c", "rm -Rf /var/lib/mysql/lost+found" ]
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: xpipe-tracker-db-volume
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
        #- name: init-mysqldata
        #  image: mysql:8.3.0
        #  command: [ "bash", "-c", "microdnf install rsync && rsync -ravP /var/lib/mysql/ /data/" ]
        #  volumeMounts:
        #    - mountPath: /data
        #      name: xpipe-tracker-db-volume
        #  resources:
        #    requests:
        #      cpu: 10m
        #      memory: 10Mi
        - name: init-mysql
          image: busybox
          command: [ "sh", "-c", "chown -R 999:999 /var/lib/mysql" ]
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: xpipe-tracker-db-volume
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
      containers:
      - env:
        - name: MYSQL_MAX_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              key: MYSQL_MAX_CONNECTIONS
              name: xpipe-tracker-db-config
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: xpipe-tracker-db-secret
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: xpipe-tracker-db-secret
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: xpipe-tracker-db-secret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: xpipe-tracker-db-secret
        image: mysql:8.3.0
        imagePullPolicy: IfNotPresent
#        livenessProbe:
#          exec:
#            command:
#            - /bin/sh
#            - -i
#            - -c
#            - mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}
#          failureThreshold: 3
#          initialDelaySeconds: 30
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 1
        name: xpipe-tracker-db
        ports:
        - containerPort: 3306
          protocol: TCP
#        readinessProbe:
#          exec:
#            command:
#            - /bin/sh
#            - -ec
#            - set -ex
#            - mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1'
#          failureThreshold: 3
#          initialDelaySeconds: 5
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 1
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 1024Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: xpipe-tracker-db-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: xpipe-tracker-db-volume
        persistentVolumeClaim:
          claimName: xpipe-tracker-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xpipe-tracker-db
  name: xpipe-tracker-db
  namespace: xpipe-sindria
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: xpipe-tracker-db
  sessionAffinity: None
  type: ClusterIP
