apiVersion: v1
kind: ConfigMap
metadata:
  name: xpipe-auth-config
  namespace: xpipe-sindria
data:
  KEYCLOAK_PROXY_ADDRESS_FORWARDING: "true"
  KEYCLOAK_DB_VENDOR: "mysql"
  KEYCLOAK_IMPORT: "/tmp/realm-export.json"