image: sindriainc/image-builder:latest

pipelines:
  tags:
    '*':
      - step:
          name: Build Image
          script:
            - echo -e "${BLUE}Building image...${NC}"
            - bash build.sh ${DOCKERHUB_NAMESPACE}/${BITBUCKET_REPO_SLUG} ${BITBUCKET_TAG}
            - docker save ${DOCKERHUB_NAMESPACE}/${BITBUCKET_REPO_SLUG}:${BITBUCKET_TAG} --output "${BITBUCKET_REPO_SLUG}.tar"
            - cowsay -f tux "Build Success"
          services:
            - docker
          caches:
            - docker
          artifacts:
            - "*.tar"
      - step:
          name: Push Image
          script:
            - echo -e "${BLUE}Loading cached image...${NC}"
            - docker load --input "${BITBUCKET_REPO_SLUG}.tar"
            - echo -e "${BLUE}Tagging cached image...${NC}"
            - docker tag "${DOCKERHUB_NAMESPACE}/${BITBUCKET_REPO_SLUG}:${BITBUCKET_TAG}" "${DOCKERHUB_NAMESPACE}/${BITBUCKET_REPO_SLUG}:${BITBUCKET_TAG}"
            - docker tag "${DOCKERHUB_NAMESPACE}/${BITBUCKET_REPO_SLUG}:${BITBUCKET_TAG}" "${DOCKERHUB_NAMESPACE}/${BITBUCKET_REPO_SLUG}:latest"
            - echo -e "${BLUE}Login into registry...${NC}"
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
            - echo -e "${BLUE}Pushing image into registry...${NC}"
            - docker push ${DOCKERHUB_NAMESPACE}/${BITBUCKET_REPO_SLUG}:${BITBUCKET_TAG}
            - docker push ${DOCKERHUB_NAMESPACE}/${BITBUCKET_REPO_SLUG}:latest
            - echo -e "${BLUE}Cleaning local registry...${NC}"
            - docker image rm ${DOCKERHUB_NAMESPACE}/${BITBUCKET_REPO_SLUG}:${BITBUCKET_TAG}
            - docker image rm ${DOCKERHUB_NAMESPACE}/${BITBUCKET_REPO_SLUG}:latest
            - cowsay -f dragon "Well Done! New docker image is now on your registry."
          services:
            - docker