---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mc-sindria
  name: mc-sindria-world-pvc
  namespace: sindria-mc
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mc-sindria
  name: mc-sindria-logs-pvc
  namespace: sindria-mc
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mc-sindria
  name: mc-sindria-cache-pvc
  namespace: sindria-mc
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
