---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fnd-v1-api-collector
  name: fnd-v1-api-collector-static-pvc
  namespace: xpipe-cloud
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fnd-v1-api-collector
  name: fnd-v1-api-collector-media-pvc
  namespace: xpipe-cloud
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fnd-v1-api-collector
  name: fnd-v1-api-collector-generated-pvc
  namespace: xpipe-cloud
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fnd-v1-api-collector
  name: fnd-v1-api-collector-var-pvc
  namespace: xpipe-cloud
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi