
package org.cmdbuild.services.soap.client.beans;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.10
 * 2018-05-16T09:39:11.465+02:00
 * Generated source version: 3.1.10
 */

@WebFault(name = "NoSuchAlgorithmException", targetNamespace = "http://soap.services.cmdbuild.org")
public class NoSuchAlgorithmException_Exception extends Exception {
    
    private org.cmdbuild.services.soap.client.beans.NoSuchAlgorithmException noSuchAlgorithmException;

    public NoSuchAlgorithmException_Exception() {
        super();
    }
    
    public NoSuchAlgorithmException_Exception(String message) {
        super(message);
    }
    
    public NoSuchAlgorithmException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchAlgorithmException_Exception(String message, org.cmdbuild.services.soap.client.beans.NoSuchAlgorithmException noSuchAlgorithmException) {
        super(message);
        this.noSuchAlgorithmException = noSuchAlgorithmException;
    }

    public NoSuchAlgorithmException_Exception(String message, org.cmdbuild.services.soap.client.beans.NoSuchAlgorithmException noSuchAlgorithmException, Throwable cause) {
        super(message, cause);
        this.noSuchAlgorithmException = noSuchAlgorithmException;
    }

    public org.cmdbuild.services.soap.client.beans.NoSuchAlgorithmException getFaultInfo() {
        return this.noSuchAlgorithmException;
    }
}
