---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: xpipe-xdev
  name: xpipe-xdev-projects-pvc
  namespace: xpipe-dev
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: xpipe-xdev
  name: xpipe-xdev-ssh-pvc
  namespace: xpipe-dev
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: xpipe-xdev
  name: xpipe-xdev-aws-pvc
  namespace: xpipe-dev
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: xpipe-xdev
  name: xpipe-xdev-azure-pvc
  namespace: xpipe-dev
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: xpipe-xdev
  name: xpipe-xdev-kube-pvc
  namespace: xpipe-dev
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 128Mi