version: '3.9'

services:
  # =app
  app:
    image: "sindriainc/nginx-php:${NGINX_PHP_TAG}-${NGINX_PHP_VERSION}"
    container_name: "${APP_NAME}"
    #command: tail -f /dev/null
#    command: /bin/bash -c "apk update; apk add nodejs npm; chmod +x /startup.sh; /startup.sh"
    volumes:
      - "${BASE_PATH}/${PROJECT_PATH}/${CODE_PATH}:${APP_CODE_PATH}"
    hostname: "${APP_NAME}.local"
    ports:
      - "8090:80"
    networks:
      default:
        ipv4_address: "${APP_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}.local"
    #networks:
    #  vpc_app_name:
    #    ipv4_address: "${APP_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"

  # =db
  db:
    image: "mysql:${MYSQL_TAG}"
    container_name: "${APP_NAME}-db"
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      #- MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - "db:/var/lib/mysql"
    hostname: "${APP_NAME}-db.local"
    ports:
      - "33050:3306"
    networks:
      default:
        ipv4_address: "${DB_IP_ADDRESS}"
        aliases:
          - "${APP_NAME}-db.local"
    #networks:
    #  vpc_<app-name>:
    #    ipv4_address: "${DB_IP_ADDRESS}"
    #    aliases:
    #      - "${APP_NAME}.local"


# =networks
networks:
  default:
    name: "vpc_xpipe"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}

# =networks
#networks:
#  vpc_app_name:
#    external: true

# =volumes
volumes:
  db:
