<?php
/**
 * @var $block
 */

?>

<script type="text/x-magento-init">
    {
        "*": {
            'Magento_Store/switcher': 'Pipe_LanguageSelector/js/switcher'
        }
    }
</script>


<!--<script type="text/javascript">-->
<!---->
<!--    require(['notificationPoller'], function (initPoller) {-->
<!--        console.log('[XPipe] Notification Poller initialized');-->
<!--        //initPoller();-->
<!--    });-->
<!--</script>-->
