scrape_configs:
  - job_name: 'apm'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - 'tasks.apm'
        type: 'A'
        port: 9100
    static_configs:
      - targets: [ @@APM_HOSTS@@ ]