---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mc-demo
  name: mc-demo-world-pvc
  namespace: sindria-mc
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mc-demo
  name: mc-demo-logs-pvc
  namespace: sindria-mc
#provisioner: kubernetes.io/aws-ebs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi