---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mc-demo
  name: mc-demo
  namespace: sindria-mc
spec:
  ports:
  - name: minecraft
    port: 25565
    protocol: TCP
    targetPort: 25565
  - name: apm
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mc-demo
  sessionAffinity: None
  type: ClusterIP