stages:
  - build
  - test
  - push
  - deploy

.set_colors: &set_colors
  - export BLUE='\033[0;34m'
  - export YELLOW='\033[0;33m'
  - export RED='\033[0;31m'
  - export NC='\033[0m' #No Color
  - export NOW=$(date "+%Y-%m-%d_%H-%M-%S")
  
.setup_storage: &setup_storage
  - ssh $SERVER "mkdir -p $BASE_PATH/$IMAGE_NAME"
  - ssh $SERVER "mkdir -p $BASE_PATH/$IMAGE_NAME/storage"
  - ssh $SERVER "mkdir -p $BASE_PATH/$IMAGE_NAME/storage/data"
  - ssh $SERVER "mkdir -p $BASE_PATH/$IMAGE_NAME/storage/logs"

variables:
  BASE_PATH: "/home/sindria"
  IMAGE_NAME: "example-service"
  IMAGE_NAMESPACE: "registry.sindria.org/example-team"
  SERVER: "example.sindria.org"

build:docker:
  image: registry.sindria.org/devops/base-images/image-builder:latest
  stage: build
  tags:
    - docker
  only:
    - tags
  before_script:
    - *set_colors
  script:
    - echo -e "${BLUE}Building image...${NC}"
    - bash build.sh $IMAGE_NAMESPACE/$IMAGE_NAME $CI_COMMIT_TAG
    - cowsay -f tux "Build Success"

push:docker:
  image: registry.sindria.org/devops/base-images/image-builder:latest
  stage: push
  tags:
    - docker
  only:
    - tags
  before_script:
    - *set_colors
  script:
    - echo -e "${BLUE}Pushing image into registry...${NC}"
    - docker push $IMAGE_NAMESPACE/$IMAGE_NAME:$CI_COMMIT_TAG
    - docker push $IMAGE_NAMESPACE/$IMAGE_NAME:latest
    - echo #
    - echo -e "${BLUE}Cleaning local registry...${NC}"
    - docker image rm $IMAGE_NAMESPACE/$IMAGE_NAME:$CI_COMMIT_TAG
    - docker image rm $IMAGE_NAMESPACE/$IMAGE_NAME:latest
    - echo #
    - cowsay -f dragon "Well Done! New docker image is now on your registry."

deploy:app:
  image: registry.sindria.org/devops/base-images/deployer:latest
  stage: deploy
  tags:
    - default
  only:
    - tags
  before_script:
    - *set_colors
    - cp .env.production .env
    - cp docker-compose.production.yml docker-compose.yml
  script:
    - *setup_storage
    - ssh $SERVER "docker stop $IMAGE_NAME" || echo -e "${YELLOW}No such container $IMAGE_NAME${NC}"
    - ssh $SERVER "docker rm $IMAGE_NAME" || echo -e "${YELLOW}No such container $IMAGE_NAME${NC}"
    - rsync -ravP -e "ssh" --exclude='.git' --exclude='.git*' --exclude='.gitlab-ci.yml' --exclude='readme.md' --exclude='README.md' --exclude='build.sh' --exclude='storage' --exclude='src' --exclude='certs' --exclude='docker-compose.local.yml' --exclude='docker-compose.production.yml' --exclude='.env.local' --exclude='.env.production' --delete $CI_PROJECT_DIR/ $SERVER:/$BASE_PATH/$IMAGE_NAME/
    - ssh $SERVER "sudo chmod 770 $BASE_PATH/$IMAGE_NAME"
    - ssh $SERVER "docker image rm $IMAGE_NAMESPACE/$IMAGE_NAME:latest" || echo -e "${YELLOW}Image not present into this local registry${NC}"
    - ssh $SERVER "cd $BASE_PATH/$IMAGE_NAME; docker-compose up -d"
    - cowsay "Deploy Success"