<?php
/** @var Monitoring\Summary\Block\Adminhtml\Summary $block */

?>



<!-- 1:1 aspect ratio -->
<div class="embed-responsive embed-responsive-21by9">
    <iframe class="embed-responsive-item" frameborder="0" src="<?= $block->getSummaryDashboard() ?>"></iframe>
</div>



<style>
    /* Embed - bootstrap classes */

    .embed-responsive {
        position: relative;
        display: block;
        width: 100%;
        padding: 0;
        overflow: hidden;
    }
    .embed-responsive::before {
        display: block;
        content: "";
    }
    .embed-responsive .embed-responsive-item,
    .embed-responsive iframe,
    .embed-responsive embed,
    .embed-responsive object,
    .embed-responsive video {
        position: absolute;
        top: 0;
        bottom: 0;
        left: 0;
        width: 100%;
        height: 100%;
        border: 0;
    }

    .embed-responsive-21by9::before {
        padding-top: 42.85714286%;
    }


    .form-container {
        display: none !important;
    }

    label {
        display: inline-block;
        margin-bottom: 0.0rem;
    }
</style>
