<?php /** @var $block \Magento\Framework\View\Element\Template */
//dd($block);

?>

<div class="page-main-actions">
    <div class="page-actions-placeholder">

    </div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="Pipeline Runs">
            <div class="page-actions-buttons">
                <button id="back" title="Back" type="button" class="action- scalable back" onclick="setLocation('<?= $block->escapeUrl($block->getBackUrl()) ?>')"  ui-button-widget-hook-id="buttonIdd3W0G94Tai" data-ui-id="back-button">
                    <span><?= __('Back') ?></span>
                </button>
            </div>
        </div>
    </div>
</div>


<div class="page-main-actions devopsui-backnav">
    <button type="button"
            class="action- scalable back"
            onclick="setLocation('<?= $block->escapeUrl($block->getBackUrl()) ?>')">
        <span><?= __('Back') ?></span>
    </button>
</div>