/*
 * CMDBuild has been developed and is managed by Tecnoteca srl
 * You can use CMDBuild according to the license
 */
package org.cmdbuild.modeldiff.data;

import static com.google.common.base.Preconditions.checkNotNull;
import org.cmdbuild.dao.beans.Card;

/**
 * Represents {@link Card} data.
 * 
 * <b>Note</b>: is a String to be able to handle an <i>UUID</i> generated by 
 * UI client, to be able to handle references to a newly created card; the {@link CmCardDataApplier}
 * will handle proper substitution with real persisted id.
 * 
 * @author afelice
 */
public class CmCardData {
    
    public static final String UNDEFINED_ID = "0";
    
    protected final String classeName;
    protected String id = UNDEFINED_ID;

    public CmCardData(String classeName) {
        this.classeName = checkNotNull(classeName);        
    }    

    public CmCardData(String classeName, Long id) {
        this(classeName, String.valueOf(id));
    }
    
    public CmCardData(String classeName, String id) {
        this(classeName);
        
        this.id = checkNotNull(id);
    }

    public String getId() {
        return String.valueOf(id);
    }

    public String getClasseName() {
        return classeName;
    }   
    
    @Override
    public String toString() {
        return "CmCardData{id =< %s >=}".formatted(id);
    }
    
}
