# yaml-language-server: $schema=http://team.cmdbuild.org/resources/cmdbuild/etl/waterway/config/v1/schema.json
description: MyConfig
notes: 
items:
    -
        gate: MyGate
        handlers: []
        