---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-cms
  name: example-cms
  namespace: example-project
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: example-cms
  sessionAffinity: None
  type: ClusterIP
