name: BaseImages CI NginxPHP LocalMagento

on:
  push:
    branches:
      - 'master'
    paths:
      - BaseImages/nginx-php/local-magento/**/*.*
      - .github/workflows/baseimages-ci-nginxphp-localmagento.yml

defaults:
  run:
    working-directory: BaseImages/nginx-php/local-magento

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env release
      run: echo "RELEASE_VERSION=6.0.0-local-magento" >> $GITHUB_ENV
    - name: Set env slug
      run: echo "REPO_SLUG=nginx-php" >> $GITHUB_ENV
    - uses: docker/setup-qemu-action@v2
    - name: Login into registry
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
    - name: Build and Publish Image
      env:
        DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}
      run: bash build_all.sh ${DOCKERHUB_NAMESPACE}/${REPO_SLUG} ${RELEASE_VERSION}