name: Core Web BasePortal V1

on:
  push:
    branches:
      - 'tmp'
    paths:
      - Core/V1/Web/core-web-baseportal-v1/**/*.*
      - .github/workflows/core-web-baseportal-v1.yml

env:
  BLUE: '\033[0;34m'
  YELLOW: '\033[0;33m'
  RED: '\033[0;31m'
  NC: '\033[0m' #No Color
  REPO_SLUG: "core-web-baseportal-v1"
  RELEASE_VERSION: "1.0.0"
  MONOREPO_BUSINESS_DOMAIN: "Core"
  XPIPE_CORE_MAJOR_VERSION: "V1"
  MONOREPO_BUSINESS_ROLE: "Web"
  WOPR_NAMESPACE: "xpipe-cloud"
  MONOREPO_PRODUCT_DOMAIN: "Products"
  MONOREPO_PRODUCT_NAME: "XPipe"

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      BLUE: ${{ env.BLUE }}
      YELLOW: ${{ env.YELLOW }}
      RED: ${{ env.RED }}
      NC: ${{ env.NC }}
      REPO_SLUG: ${{ env.REPO_SLUG }}
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      MONOREPO_BUSINESS_DOMAIN: ${{ env.MONOREPO_BUSINESS_DOMAIN }}
      WOPR_NAMESPACE: ${{ env.WOPR_NAMESPACE }}
    steps:
      - run: echo "Exposing env vars"

  validate:
    uses: SindriaInc/XPipe/.github/workflows/job-no-validate-global.yml@master
    needs: vars
    secrets:
      _DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      _DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    with:
      COMMON_CONTAINER_STAGING_PATH: ${{ vars.COMMON_CONTAINER_STAGING_PATH }}
      REPO_SLUG: ${{ needs.vars.outputs.REPO_SLUG }}
      RELEASE_VERSION: ${{ needs.vars.outputs.RELEASE_VERSION }}
      DOCKERHUB_PRIVATE_NAMESPACE: ${{ vars.DOCKERHUB_PRIVATE_NAMESPACE }}
      DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}
      MONOREPO_BUSINESS_DOMAIN: ${{ needs.vars.outputs.MONOREPO_BUSINESS_DOMAIN }}

  build_publish:
    uses: SindriaInc/XPipe/.github/workflows/job-ci-buildpublish-oci.yml@master
    needs:
      - vars
      - validate
    secrets:
      _DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      _DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
    with:
      COMMON_CONTAINER_STAGING_PATH: ${{ vars.COMMON_CONTAINER_STAGING_PATH }}
      REPO_SLUG: ${{ needs.vars.outputs.REPO_SLUG }}
      RELEASE_VERSION: ${{ needs.vars.outputs.RELEASE_VERSION }}
      DOCKERHUB_PRIVATE_NAMESPACE: ${{ vars.DOCKERHUB_PRIVATE_NAMESPACE }}
      DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}
      MONOREPO_BUSINESS_DOMAIN: ${{ needs.vars.outputs.MONOREPO_BUSINESS_DOMAIN }}

  deploy:
    uses: SindriaInc/XPipe/.github/workflows/job-cd-deploy-wopr.yml@master
    needs:
      - vars
      - build_publish
    secrets:
      _DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      _DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      _WOPR_KUBECONFIG: ${{ secrets.WOPR_KUBECONFIG }}
    with:
      COMMON_CONTAINER_STAGING_PATH: ${{ vars.COMMON_CONTAINER_STAGING_PATH }}
      REPO_SLUG: ${{ needs.vars.outputs.REPO_SLUG }}
      RELEASE_VERSION: ${{ needs.vars.outputs.RELEASE_VERSION }}
      DOCKERHUB_PRIVATE_NAMESPACE: ${{ vars.DOCKERHUB_PRIVATE_NAMESPACE }}
      DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}
      MONOREPO_BUSINESS_DOMAIN: "IaC"
      WOPR_NAMESPACE: ${{ needs.vars.outputs.WOPR_NAMESPACE }}

  postdeploy:
    uses: SindriaInc/XPipe/.github/workflows/job-cd-postdeploy-magento.yml@master
    needs:
      - vars
      - deploy
    secrets:
      _DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      _DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      _WOPR_KUBECONFIG: ${{ secrets.WOPR_KUBECONFIG }}
    with:
      COMMON_CONTAINER_STAGING_PATH: ${{ vars.COMMON_CONTAINER_STAGING_PATH }}
      REPO_SLUG: ${{ needs.vars.outputs.REPO_SLUG }}
      RELEASE_VERSION: ${{ needs.vars.outputs.RELEASE_VERSION }}
      DOCKERHUB_PRIVATE_NAMESPACE: ${{ vars.DOCKERHUB_PRIVATE_NAMESPACE }}
      DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}
      MONOREPO_BUSINESS_DOMAIN: "IaC"
      WOPR_NAMESPACE: ${{ needs.vars.outputs.WOPR_NAMESPACE }}

###
