name: Core CI Ecommerce

on:
  push:
    branches:
      - 'master'
    paths:
      - Core/xpipe-ecommerce/**/*.*
      - .github/workflows/core-ci-ecommerce-void.yml

defaults:
  run:
    working-directory: Core/xpipe-ecommerce

jobs:
  build_publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env release
      run: cat VERSION.env >> $GITHUB_ENV
    - name: Set env slug
      run: cat REPO.env >> $GITHUB_ENV
    - uses: docker/setup-qemu-action@v2
    - name: Login into registry
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
    - name: Build and Publish Image
      env:
        DOCKERHUB_PRIVATE_NAMESPACE: ${{ vars.DOCKERHUB_PRIVATE_NAMESPACE }}
      run: bash build_all.sh ${DOCKERHUB_PRIVATE_NAMESPACE}/${REPO_SLUG} ${RELEASE_VERSION}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env release
        run: cat VERSION.env >> $GITHUB_ENV
      - name: Set env slug
        run: cat REPO.env >> $GITHUB_ENV
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.WOPR_KUBECONFIG }}
        with:
          args: get pods -n xpipe-cloud