name: IaC noOps MH Certs

on:
  push:
    branches:
      - 'master'
    paths:
      #- IaC/sindria-ingress/**/*.*
      - .github/workflows/iac-no-mh-certs.yml

defaults:
  run:
    working-directory: IaC

jobs:
  certs_1:
    uses: SindriaInc/XPipe/.github/workflows/job-no-certs-route53.yml@master
    secrets:
      _AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      _AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      AWS_DEFAULT_REGION: "eu-central-1"
      CRT_CERTBOT_CACHE: "sindria-mh-certbot-cache"
      CRT_CERTBOT_EMAIL: ${{ vars.CRT_CERTBOT_EMAIL }}
      CRT_CERTBOT_DOMAIN: "monsterhunter.it"

  certs_2:
    uses: SindriaInc/XPipe/.github/workflows/job-no-certs-route53.yml@master
    secrets:
      _AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      _AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    with:
      AWS_DEFAULT_REGION: "eu-central-1"
      CRT_CERTBOT_CACHE: "sindria-mh-certbot-cache"
      CRT_CERTBOT_EMAIL: ${{ vars.CRT_CERTBOT_EMAIL }}
      CRT_CERTBOT_DOMAIN: "monster-hunter.it"

#
