name: IaC CD Ecommerce Cloud

on:
  push:
    branches:
      - 'master'
    paths:
      - Iac/xpipe-cloud/xpipe-ecommerce/**/*.*
      - .github/workflows/iac-cd-ecommerce-cloud.yml

env:
  BLUE: '\033[0;34m'
  YELLOW: '\033[0;33m'
  RED: '\033[0;31m'
  NC: '\033[0m' #No Color
  REPO_SLUG: "xpipe-ecommerce"
  RELEASE_VERSION: "1.0.2"
  MONOREPO_BUSINESS_DOMAIN: "IaC"
  WOPR_NAMESPACE: "xpipe-cloud"

jobs:
  vars:
    runs-on: ubuntu-latest
    outputs:
      BLUE: ${{ env.BLUE }}
      YELLOW: ${{ env.YELLOW }}
      RED: ${{ env.RED }}
      NC: ${{ env.NC }}
      REPO_SLUG: ${{ env.REPO_SLUG }}
      RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      MONOREPO_BUSINESS_DOMAIN: ${{ env.MONOREPO_BUSINESS_DOMAIN }}
      WOPR_NAMESPACE: ${{ env.WOPR_NAMESPACE }}
    steps:
      - run: echo "Exposing env vars"

  deploy:
    uses: SindriaInc/XPipe/.github/workflows/job-cd-deploy-wopr.yml@master
    needs:
      - vars
    secrets:
      _DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      _DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      _WOPR_KUBECONFIG: ${{ secrets.WOPR_KUBECONFIG }}
    with:
      COMMON_CONTAINER_STAGING_PATH: ${{ vars.COMMON_CONTAINER_STAGING_PATH }}
      REPO_SLUG: ${{ needs.vars.outputs.REPO_SLUG }}
      RELEASE_VERSION: ${{ needs.vars.outputs.RELEASE_VERSION }}
      DOCKERHUB_PRIVATE_NAMESPACE: ${{ vars.DOCKERHUB_PRIVATE_NAMESPACE }}
      DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}
      MONOREPO_BUSINESS_DOMAIN: ${{ needs.vars.outputs.MONOREPO_BUSINESS_DOMAIN }}
      WOPR_NAMESPACE: ${{ needs.vars.outputs.WOPR_NAMESPACE }}