name: Pipelines V1 Tpl Jobs

on:
  push:
    branches:
      - 'master'
    paths:
      - Pipelines/V1/Tpl/pipelines-v1-tpl-jobs/**/*.*
      - .github/workflows/pipelines-v1-tpl-jobs.yml

defaults:
  run:
    working-directory: Pipelines/V1/Tpl/pipelines-v1-tpl-jobs

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env release
      run: echo "RELEASE_VERSION=1.0.0" >> $GITHUB_ENV
    - name: Set env slug
      run: echo "REPO_SLUG=pipelines-v1-tpl-jobs" >> $GITHUB_ENV
    - name: Login into registry
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin