name: Routines CI CertsOVH

on:
  push:
    branches:
      - 'master'
    paths:
      - Routines/xpipe-no-certs-ovh/**/*.*
      - .github/workflows/routines-no-certsovh-void.yml

defaults:
  run:
    working-directory: Routines/xpipe-no-certs-ovh

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env release
      run: cat VERSION.env >> $GITHUB_ENV
    - name: Set env slug
      run: cat REPO.env >> $GITHUB_ENV
    - uses: docker/setup-qemu-action@v2
    - name: Login into registry
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
    - name: Build and Publish Image
      env:
        DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}
      run: bash build_all.sh ${DOCKERHUB_NAMESPACE}/${REPO_SLUG} ${RELEASE_VERSION}