name: Security CI Kali

on:
  push:
    branches:
      - 'master'
    paths:
      - Security/kali/**/*.*
      - .github/workflows/security-ci-kali-void.yml

defaults:
  run:
    working-directory: Security/kali

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env release
      run: echo "RELEASE_VERSION=3.0.0" >> $GITHUB_ENV
    - name: Set env slug
      run: echo "REPO_SLUG=kali" >> $GITHUB_ENV
    - uses: docker/setup-qemu-action@v2
    - name: Login into registry
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: echo ${DOCKERHUB_PASSWORD} | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
    - name: Build and Publish Image
      env:
        DOCKERHUB_NAMESPACE: ${{ vars.DOCKERHUB_NAMESPACE }}
      run: bash build_all.sh ${DOCKERHUB_NAMESPACE}/${REPO_SLUG} ${RELEASE_VERSION}