<?php
/** @var \Magento\Backend\Block\Page\Header $block */
$part = $block->getShowPart();
//dd($part);
?>
<?php if ($part === 'user') : ?>
    <div class="admin-user admin__action-dropdown-wrap">
        <a
                href="<?= /* @noEscape */ $block->getUrl('adminhtml/system_account/index') ?>"
                class="admin__action-dropdown"
                title="<?= $block->escapeHtml(__('My Account')) ?>"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown">
                <span class="admin__action-dropdown-text">
                    <span class="admin-user-account-text"><?= $block->escapeHtml($block->getUser()->getUserName()) ?></span>
                </span>
        </a>
        <ul class="admin__action-dropdown-menu">
            <?php if ($block->getAuthorization()->isAllowed('Magento_Backend::myaccount')) : ?>
                <li>
                    <a
                            href="<?= /* @noEscape */ $block->getUrl('adminhtml/system_account/index') ?>"
                        <?= /* @noEscape */ $block->getUiId('user', 'account', 'settings') ?>
                            title="<?= $block->escapeHtml(__('Account Setting')) ?>">
                        <?= $block->escapeHtml(__('Account Setting')) ?> (<span class="admin-user-name"><?= $block->escapeHtml($block->getUser()->getUserName()) ?></span>)
                    </a>
                </li>
            <?php endif; ?>
            <li>
                <a
                        href="<?= /* @noEscape */ $block->getBaseUrl() ?>"
                        title="<?= $block->escapeHtml(__('Customer View')) ?>"
                        target="_blank" class="store-front">
                    <?= $block->escapeHtml(__('Customer View')) ?>
                </a>
            </li>
            <li>
                <a
                        href="<?= /* @noEscape */ $block->getLogoutLink() ?>"
                        class="account-signout"
                        title="<?= $block->escapeHtml(__('Sign Out')) ?>">
                    <?= $block->escapeHtml(__('Sign Out')) ?>
                </a>
            </li>
        </ul>
    </div>


<div class="terminal-wrapper admin__action-dropdown-wrap">
    <a class="terminal-action" href="<?php echo $block->getUrl('terminal/index/index') ?>" title="Terminal">
        <img src="<?php echo $block->getViewFileUrl('Lab_Terminal::images/terminal-icon.svg'); ?>" alt="Terminal" width="22" height="22"/>
    </a>
</div>

<style>
    .admin-user {
        float: right;
        line-height: 1.36;
        margin-left: 0.6rem;
        z-index: 490;
    }

    .terminal-wrapper {
        float: right;
        line-height: 2.36;
        margin-left: 0.3rem;
        z-index: 490;
    }

    .terminal-action {
        color: #41362f;
        height: 3.3rem;
        /*padding: .75rem 2rem .65rem;*/
    }

    .terminal-action img {
        vertical-align: middle;
    }
</style>

<?php endif; ?>